### ISSUE TITLE
您好，留意到这个这个项目，刚好想用，请问现在是不是还没正式完成？

### ISSUE THREAD

**Issue by qikong333** [pipipi-pikachu/PPTist#10]
如果可以的话想参与进来

**Comment by pipipi-pikachu** [comment]
事实上这个项目并没有一个较长远的计划，目前我最开始计划的基础功能都已经完成了，但现在实际体验下来，收到了不少建议和需求，还在持续更新中。
[暂时的计划可以看这里](https://github.com/pipipi-pikachu/PPTist#-todo)，当然了，还有很多小功能没有列出来。
目前核心功能主要还差最后的导入和导出，另一个比较缺的就是测试了。[具体贡献代码的方式看这里](https://github.com/pipipi-pikachu/PPTist#-%E8%B4%A1%E7%8C%AE%E4%BB%A3%E7%A0%81)
