### ISSUE TITLE
导出图片，随着页面增多，图片宽度会减少

### ISSUE THREAD

**Issue by EastSmartEducation** [pipipi-pikachu/PPTist#105]
**注意**
1. 请在提问前先尝试搜索历史 Issue 记录，避免重复的问题。
2. 请确保提问时已经仔细阅读过 README 中的相关事项。

**问题描述**  
请尽量简洁、完整地描述你遇到的bug，至少包括以下部分（如有必要，可提供截图）：
1. 问题触发的条件/操作流程
2. 期望表现与实际表现

**环境信息**  
至少包含以下部分：
1. 系统环境(Mac or Windows)
2. 浏览器环境(如：Chrome v89.0.4389.114)

**Comment by pipipi-pikachu** [comment]
导出图片宽度应该是固定的 1600 像素，可以提供一下图片详细信息截图

**Comment by EastSmartEducation** [comment]
可以试一下，当页数足够多时，图片最大高度为16384像素，超过这个高度就会保持高度不变进行缩放，这个可能是canvas高度限制的的，

**Comment by pipipi-pikachu** [comment]
对于这类超长图暂时看起来无法解决，现在添加了导出范围配置，这类情况可分批多次导出。
