### ISSUE TITLE
MacBook 上使用Safari幻灯片放映需要点击两次才能成功

### ISSUE THREAD

**Issue by BOKE2014** [pipipi-pikachu/PPTist#106]
MacBook Air上使用Safari幻灯片放映需要点击两次才能成功。
第一次点击会闪一下，第二次点击可以进入放映模式。

设备：MacBook Air macOS Big Sur 11.6.6
浏览器：Safari

其他浏览器正常，如：chrome和Edge

**Comment by pipipi-pikachu** [comment]
手上没有 mac 设备，所以未针对 Safari 进行过测试，我后面找时间装个虚拟机集中测试下吧。

**Comment by BOKE2014** [comment]
> 手上没有 mac 设备，所以未针对 Safari 进行过测试，我后面找时间装个虚拟机集中测试下吧。

谢谢🙏

**Comment by pipipi-pikachu** [comment]
> MacBook Air上使用Safari幻灯片放映需要点击两次才能成功。 第一次点击会闪一下，第二次点击可以进入放映模式。
> 
> 设备：MacBook Air macOS Big Sur 11.6.6 浏览器：Safari
> 
> 其他浏览器正常，如：chrome和Edge

我调整了一下全屏判断相关的逻辑，可以试试现在是否能在 safari 下正常工作，我也很不确定..

**Comment by claviering** [comment]
It work when click once `幻灯片放映` but it make other `bug`.  We must press twice `ESC` to exit Screening in Safari. 😂

[bilibili](https://www.bilibili.com/video/BV1dB4y1Q7DY/)

**Comment by claviering** [comment]
`fullscreenchange`event not work in safari 😂

**Comment by BOKE2014** [comment]
> It work when click once `幻灯片放映` but it make other `bug`. We must press twice `ESC` to exit Screening in Safari. 😂
> 
> [bilibili](https://www.bilibili.com/video/BV1dB4y1Q7DY/)

**Comment by BOKE2014** [comment]
> > MacBook Air上使用Safari幻灯片放映需要点击两次才能成功。 第一次点击会闪一下，第二次点击可以进入放映模式。
> > 设备：MacBook Air macOS Big Sur 11.6.6 浏览器：Safari
> > 其他浏览器正常，如：chrome和Edge
> 
> 我调整了一下全屏判断相关的逻辑，可以试试现在是否能在 safari 下正常工作，我也很不确定..
打开的一下没问题了，退出的时候点击退出键没问题，但是如果用键盘的ESC需要两次。

**Comment by BOKE2014** [comment]
> It work when click once `幻灯片放映` but it make other `bug`. We must press twice `ESC` to exit Screening in Safari. 😂
> 
> [bilibili](https://www.bilibili.com/video/BV1dB4y1Q7DY/)

Yea， I found it as well.
