### ISSUE TITLE
启动时报错：ERROR in src/store/snapshot.ts:93:45 TS2345: Argument of type 'IndexableTypeArray' is not assignable to parameter of type 'number[]'.

### ISSUE THREAD

**Issue by renyawen** [pipipi-pikachu/PPTist#107]
![image](https://user-images.githubusercontent.com/54051371/169790937-f4f28ee3-ff35-4c25-a144-95c088833f32.png)
需要改成
![image](https://user-images.githubusercontent.com/54051371/169790487-c551d331-45ec-4d3a-bf61-89bbafa00bc1.png)

**Comment by pipipi-pikachu** [comment]
在 node_modules 中检查一下你的 dexie 版本，如果不同，可能是因为你删除过 package-lock 文件导致的，重新拉取项目安装，或者将 dexie 降级和仓库相同的版本即可。
![image](https://user-images.githubusercontent.com/22936489/169793261-45f0b045-e6db-4c3d-9d03-ead7e0ec0170.png)

如果是版本问题，那个地方加上断言虽然不报错，但还是会有其他bug，因为 dexie 的 3.2 版本和老版本有不兼容的地方。
