### ISSUE TITLE
导出pdf对表格颜色没有显示，

### ISSUE THREAD

**Issue by EastSmartEducation** [pipipi-pikachu/PPTist#108]
1、导出pdf，表格的表头的背景没有导出，另外我默认使用的A4尺寸，可以加个A4尺寸吗
2、导出图片，我添加了30个空白页，导出时候，页面高度保持在16384，宽度等比缩小，使用的谷歌浏览器；这个是我使用jspdf截取图片想获得pdf时候，发现这个问题；

**Comment by pipipi-pikachu** [comment]
1 见 [常见问题](https://github.com/pipipi-pikachu/PPTist#-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) 中 打印 / 导出 PDF相关
2 是重复的问题 #105

**Comment by EastSmartEducation** [comment]
好的

**Comment by pipipi-pikachu** [comment]
另外，不计划单独添加任何打印尺寸，但会添加相关配置，来允许使用浏览器的打印尺寸选项（但不会进行尺寸自适应优化）
