### ISSUE TITLE
【BUG】由于复制粘贴撤销存在indexDB，导致双开或者多个编辑区之间ppt复制粘贴撤销异常

### ISSUE THREAD

**Issue by kankanol1** [pipipi-pikachu/PPTist#111]
**问题明细**
 1. 课件复制粘贴步骤数据保存在indexDB，并且数据库名为：SnapshotDatabase ，表：snapshots，多个页面公用同一个数据表导致在不同页面复制粘贴撤销异常显示。
 
```js
import Dexie from 'dexie'
import { Slide } from '@/types/slides'

export interface Snapshot {
  index: number;
  slides: Slide[];
}

class SnapshotDatabase extends Dexie {
  public snapshots: Dexie.Table<Snapshot, number>

  public constructor() {
    super('SnapshotDatabase')
    this.version(1).stores({
      snapshots: '++id'
    })
    this.snapshots = this.table('snapshots')
  }
}

export const snapshotDB = new SnapshotDatabase()
```
 2. 具体场景：
      首先渲染A课件，然后渲染B课件，数据库中数据为B课件缓存，然后把B课件部分ppt复制粘贴到A课件，然后一直撤销，因为数据库初始渲染A被B覆盖了，所以在A课件页面一直撤销就会显示B课件了。

**期望结果**
1、希望每次进入创建新表，并对超过一定日期的数据表进行删除，比如设定一天，每次进入删除一天前的数据表，既可以解决双开或者更能多编辑页面之间的复制粘贴，也可以通过定时清理过时表，减少垃圾存储。

**Comment by pipipi-pikachu** [comment]
嗯，这都不仅是复制粘贴，而是整个历史记录冲突了，这确实是会导致bug，现在已更新为每个页面使用独立的库，我之前没有还原过你的场景，现在你可以试试是否能正确工作了

**Comment by kankanol1** [comment]
非常感谢，问题解决了。
