### ISSUE TITLE
能否增加一个首行缩进

### ISSUE THREAD

**Issue by BOKE2014** [pipipi-pikachu/PPTist#112]
文字编辑增加首行缩进。

谢谢

**Comment by BOKE2014** [comment]
谢谢作者更新！经过测试这似乎是文字段落的整体缩进而不是首行缩进。再次感谢！
![截屏2022-05-29 18 20 02](https://user-images.githubusercontent.com/35056286/170863219-31cf6f51-d293-4a36-a701-bf9e512cdb25.png)

**Comment by pipipi-pikachu** [comment]
你图上这个是对应PPT中的增加减少缩进功能。
首行缩进在下面

**Comment by BOKE2014** [comment]
> 你图上这个是对应PPT中的增加减少缩进功能。 首行缩进在下面

谢谢！超级好！

**Comment by BOKE2014** [comment]
> 你图上这个是对应PPT中的增加减少缩进功能。 首行缩进在下面

谢谢！超级好！
