### ISSUE TITLE
[Feature request]demo Blogger

### ISSUE THREAD

**Issue by goddits** [pipipi-pikachu/PPTist#113]
**注意**
Blogger hello，I would like to ask you how SVG works by following the synchronization function on the left side of your slide，Convenient to guide no

**Comment by pipipi-pikachu** [comment]
我没有太理解你的意思，同步功能是指缩略图？

**Comment by goddits** [comment]
![image](https://user-images.githubusercontent.com/75118230/170620473-9b76f5cb-e836-4768-87a6-d1840b91f885.png)
对的，是缩略图，滑动右边大的图，左边小的缩略图跟着同步，感谢回复

**Comment by pipipi-pikachu** [comment]
因为两边绑定的是 store 中的同一份数据
https://github.com/pipipi-pikachu/PPTist/blob/7b07629a5840e3c890d5a38cf54a90cb8dc22f12/src/store/slides.ts#L35
任意一边修改当前索引或者修改幻灯片内容的数据，另一边就会自动同步了呀

**Comment by goddits** [comment]
非常感谢大佬
