### ISSUE TITLE
输出PDF，在移动端（安卓）使用adobe reader上下两页显示不全

### ISSUE THREAD

**Issue by BOKE2014** [pipipi-pikachu/PPTist#115]
上下两个slides显示不全，用手指缩放后仍然无法看到第一张和最后一张slides。

这个有办法解决吗？

![WechatIMG341](https://user-images.githubusercontent.com/35056286/170851780-8c9d1783-4fde-462f-8047-dd7f01e198cb.jpeg)

![WechatIMG342](https://user-images.githubusercontent.com/35056286/170851783-c589ab98-9ef3-48a8-a25a-cbb3aac4fc1a.jpeg)

**Comment by pipipi-pikachu** [comment]
。。这是这个APP的顶部和底部工具栏啊，不是显示不全是被挡住了
