### ISSUE TITLE
请教作者怎么改变图表文字大小和文字颜色

### ISSUE THREAD

**Issue by BOKE2014** [pipipi-pikachu/PPTist#117]
如图：全屏的时候文字太小了，看不清
![截屏2022-06-03 21 43 44](https://user-images.githubusercontent.com/35056286/171867219-d07aa4d2-d5d1-4ec4-931f-06a57b0e32b2.png)

**Comment by pipipi-pikachu** [comment]
文字大小修改不支持，文字颜色可以通过修改网格颜色调整
