### ISSUE TITLE
移动端编辑器反馈

### ISSUE THREAD

**Issue by BOKE2014** [pipipi-pikachu/PPTist#118]
1、iPad layout：Safari，Firefox，Chrome和Edge

（1）Safari和Firefox：横屏时保持了PC的layout，功能丰富，比较好用。竖屏时仍然是PC端layout但是slide的工具条的layout混乱了，如果竖屏是切换到手机端layout，或者折叠工具条有下拉菜单就完美了。
![WechatIMG360](https://user-images.githubusercontent.com/35056286/172079264-9cc87ca6-efb3-479b-a48d-c6376e24a8a8.png)
![WechatIMG362](https://user-images.githubusercontent.com/35056286/172079262-25d5ab61-f711-4627-bc98-fe559790a3b4.png)

（2）Chrome和Edge：横竖屏都是手机端的layout，作者能否考虑做些设置iPad横屏时保持PC的layout，竖屏时切换到手机的layout？

![WechatIMG363](https://user-images.githubusercontent.com/35056286/172079329-acfbdaff-b858-4a9a-b4d9-23bee4cd72e7.png)
![WechatIMG364](https://user-images.githubusercontent.com/35056286/172079337-c033e3e0-e1b8-4d0f-9d09-b22131affe2c.png)

2、手机端：正常，可用，基本的操作没有问题。

3、字体选择
iPad端的字体选择比PC端少很多（应该是统一按照手机端做的），有些不方便，作者可否考虑给iPad补充一些？
![WechatIMG361](https://user-images.githubusercontent.com/35056286/172079534-2f220f23-866e-41f8-b301-a0eb11ffbeb1.png)

谢谢！

**Comment by pipipi-pikachu** [comment]
移动端（无论横竖屏、pad还是手机）都应该进入你说的手机端界面才对，Safari和Firefox暂不兼容，你看到的自动进入了PC界面其实是bug。
这里强调一下，在移动端进入的PC界面是完全未经处理的，不保证功能正常使用，也不在后期维护范围，所以不会做移动端自动打开PC界面的功能，如果确实想在移动端使用PC布局，在[常见问题里](https://github.com/pipipi-pikachu/PPTist#-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)有提到，直接在浏览器切换电脑模式就行（大部分移动端浏览器都有这个功能）。
最后字体那块，web应用的字体和桌面应用不一样，它是依赖系统字体的，就算加上一堆手机和平板上的字体，到了电脑上也显示不出来，就没有意义。生产环境下正确的做法可参考在线字体，由线上提供，本项目只是不依赖服务端的示例，做不到这个。

**Comment by BOKE2014** [comment]
> 移动端（无论横竖屏、pad还是手机）都应该进入你说的手机端界面才对，Safari和Firefox暂不兼容，你看到的自动进入了PC界面其实是bug。 这里强调一下，在移动端进入的PC界面是完全未经处理的，不保证功能正常使用，也不在后期维护范围，所以不会做移动端自动打开PC界面的功能，如果确实想在移动端使用PC布局，在[常见问题里](https://github.com/pipipi-pikachu/PPTist#-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)有提到，直接在浏览器切换电脑模式就行（大部分移动端浏览器都有这个功能）。 最后字体那块，web应用的字体和桌面应用不一样，它是依赖系统字体的，就算加上一堆手机和平板上的字体，到了电脑上也显示不出来，就没有意义。生产环境下正确的做法可参考在线字体，由线上提供，本项目只是不依赖服务端的示例，做不到这个。

OK 🙏
