### ISSUE TITLE
作者有空可以看看这个PPT项目的实时投票

### ISSUE THREAD

**Issue by BOKE2014** [pipipi-pikachu/PPTist#122]
这也是一个GitHub上的项目，总体比较粗糙，可用性不强，但是有个实时投票还是不错的，做个演讲还可以和观众实时互动一下，作者有空看看能否在PPTist上面有个类似的功能。

https://app.deckdeckgo.com/

https://github.com/deckgo/deckdeckgo

**Comment by pipipi-pikachu** [comment]
这边不接受个性化/定制化/具体业务需求， DeckDeckGo 是组合式插件集合，本就是开发者自己随意组装的，本项目产出的更接近成品，添加各种非普适性需求对开发者来说只会是负担，

**Comment by BOKE2014** [comment]
> 这边不接受个性化/定制化/具体业务需求， DeckDeckGo 是组合式插件集合，本就是开发者自己随意组装的，本项目产出的更接近成品，添加各种非普适性需求对开发者来说只会是负担，

谢谢作者反馈，本无意给您增加任何开发负担，只是觉得这样的功能放在PPT里可以和用户有互动挺好的。作者花时间和精力弄PPTIST开源给大家确实已经很好了非常接近成品了。谢谢

**Comment by pipipi-pikachu** [comment]
> > 这边不接受个性化/定制化/具体业务需求， DeckDeckGo 是组合式插件集合，本就是开发者自己随意组装的，本项目产出的更接近成品，添加各种非普适性需求对开发者来说只会是负担，
> 
> 谢谢作者反馈，本无意给您增加任何开发负担，只是觉得这样的功能放在PPT里可以和用户有互动挺好的。作者花时间和精力弄PPTIST开源给大家确实已经很好了非常接近成品了。谢谢

额😂你大概误会我的意思了，不是说增大我的负担这个意思，而是说本项目初衷是希望提供一套web PPT 的方案和基础实现，希望帮助别人可以参考或直接在这个基础上来扩展出自己的业务，如果本项目内添加了各种不具备普适性的功能，别人拿到这个项目再去扩展就会是负担

**Comment by BOKE2014** [comment]
> 

明白滴

**Comment by BOKE2014** [comment]
> 

明白
