### ISSUE TITLE
表格合并单元格后，再复制粘贴到PPTist中，识别不了格式

### ISSUE THREAD

**Issue by beifeng5620** [pipipi-pikachu/PPTist#123]
在PPTist中新建一个1X1的表格，双击PPTist表格进行编辑，粘贴来自本地的已合并的单元格的表格。PPTist表格没有自动扩充，格式有误

**Comment by beifeng5620** [comment]
wps word表格
![](https://github.com/beifeng5620/StaticPic/blob/sp/screenshot/Screenshot0608-1018.jpg?raw=true)

PPTist插入
![](https://github.com/beifeng5620/StaticPic/blob/sp/screenshot/Screenshot0608-1018-1.jpg?raw=true)

**Comment by pipipi-pikachu** [comment]
这倒不是合并单元格的问题，而是现在本来就只支持粘贴来自Excel的数据。

也许后面可以看看是否可以兼容粘贴更多格式的内容。

**Comment by beifeng5620** [comment]
感谢解答
