### ISSUE TITLE
建议作者恢复文字框以前的状态

### ISSUE THREAD

**Issue by BOKE2014** [pipipi-pikachu/PPTist#124]
目前不打字文字框自动消失在实际场景里有点麻烦：

1、添加一个文字框，如果想输入一些符号，如：字母、序号、数学、箭头、图形等，鼠标一离开文字框就消失了非常不方便。只能先随便敲几个字加了符号再删除文字。
2、添加文字框后不一定立刻就输入，更多的时候是先拖动文字框到合适的位置再输入，特别是空白模版的时候，现在的设置就是得强迫输入再调节位置，比较麻烦。

谢谢

**Comment by pipipi-pikachu** [comment]
已经优化了自动删除空文本框的逻辑，你的场景应该能够满足，但不会修改这个机制。
一方面老的机制存在漏洞，
另一方面需要将操作习惯对标 office PPT（符合更多人的习惯）

**Comment by pipipi-pikachu** [comment]
补充一下，空白模版这个东西应该是由另一种元素来提供，属于模板相关功能。
可以对比 office PPT ，模板的文本框和普通文本框是不一样的

**Comment by BOKE2014** [comment]
> 已经优化了自动删除空文本框的逻辑，你的场景应该能够满足，但不会修改这个机制。 一方面老的机制存在漏洞， 另一方面需要将操作习惯对标 office PPT（符合更多人的习惯）

谢谢

**Comment by BOKE2014** [comment]
> 补充一下，空白模版这个东西应该是由另一种元素来提供，属于模板相关功能。 可以对比 office PPT ，模板的文本框和普通文本框是不一样的

好，明白
