### ISSUE TITLE
反馈：添加超级链接无法点击打开的问题

### ISSUE THREAD

**Issue by BOKE2014** [pipipi-pikachu/PPTist#126]
通过右侧工具栏添加的超级链接预览模式和输出PDF后均可正常点击打开。通过右键添加的超级链接预览模式正常，但输出PDF后无法正常点击。如图所示：
![截屏2022-06-11 10 26 54](https://user-images.githubusercontent.com/35056286/173169486-1ed22235-b6f2-4d70-b826-b3413b15d43e.png)
![截屏2022-06-11 10 35 07](https://user-images.githubusercontent.com/35056286/173169491-2dc4a417-6aeb-4bf4-8810-ae49ae7196da.png)

谢谢！

**Comment by pobu168** [comment]
使用官方地址本想复现下该问题，结果’打印/导出PDF‘按钮没反应。

**Comment by BOKE2014** [comment]
> 使用官方地址本想复现下该问题，结果’打印/导出PDF‘按钮没反应。

我刚刚又试了一下可以复现

**Comment by pobu168** [comment]
> > 使用官方地址本想复现下该问题，结果’打印/导出PDF‘按钮没反应。
> 
> 我刚刚又试了一下可以复现

我这边还是调不起下载的服务
```
  const handleLoadIframe = () => {
    iframeContentWindow.focus()
    iframeContentWindow.print()
    // document.body.removeChild(iframe)
  }
```
可能是这里remove的时机问题，注释掉就可以正常调起下载PDF的界面了

**Comment by pipipi-pikachu** [comment]
> > > 使用官方地址本想复现下该问题，结果’打印/导出PDF‘按钮没反应。
> > 
> > 
> > 我刚刚又试了一下可以复现
> 
> 我这边还是调不起下载的服务
> 
> ```
>   const handleLoadIframe = () => {
>     iframeContentWindow.focus()
>     iframeContentWindow.print()
>     // document.body.removeChild(iframe)
>   }
> ```
> 
> 可能是这里remove的时机问题，注释掉就可以正常调起下载PDF的界面了

我调整了remove iframe的时机，但我不确定是否能修复这个问题（因为我一直都无法复现），可以试试最新版是否还存在这个bug

**Comment by pobu168** [comment]
> > > > 使用官方地址本想复现下该问题，结果’打印/导出PDF‘按钮没反应。
> > > 
> > > 
> > > 我刚刚又试了一下可以复现
> > 
> > 
> > 我这边还是调不起下载的服务
> > ```
> >   const handleLoadIframe = () => {
> >     iframeContentWindow.focus()
> >     iframeContentWindow.print()
> >     // document.body.removeChild(iframe)
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 可能是这里remove的时机问题，注释掉就可以正常调起下载PDF的界面了
> 
> 我调整了remove iframe的时机，但我不确定是否能修复这个问题（因为我一直都无法复现），可以试试最新版是否还存在这个bug

新版本已经解决了我出现的问题，同时，没有复现到题主的bug

**Comment by pipipi-pikachu** [comment]
导出PDF没有携带链接的功能，经过长时间思考后决定后续也不打算支持。
至于局部文本添加链接能在导出的PDF中体现，只是个美丽的误会。
不过有打算在未来统一两种添加链接的实现，届时它们导出PDF的行为也会统一（都携带链接，或都不支持）
