### ISSUE TITLE
[Bug report] 文字框多行存在空白時，切換投影片及播放投影片返回後多一行

### ISSUE THREAD

**Issue by EvanLyu** [pipipi-pikachu/PPTist#134]
文字框多空一行時，做一些操作會多一行，所有瀏覽器測試都會這樣

![截圖 2022-07-10 下午10 29 03](https://user-images.githubusercontent.com/6142091/178149192-80a5a365-6b57-453e-9440-feb769a12cd9.png)

![截圖 2022-07-10 下午10 29 12](https://user-images.githubusercontent.com/6142091/178149195-3b3012e7-e419-4a20-9e24-d581917dc085.png)

**Comment by pipipi-pikachu** [comment]
这貌似是 prosemirror 的问题 https://discuss.prosemirror.net/t/an-extra-br-is-added-in-certain-pasted-content/4730

我根据讨论中的信息进行了修复，不确定这么做是否正确，但目前看起来一切正常
