### ISSUE TITLE
打印/导出PDF无响应[Bug report]

### ISSUE THREAD

**Issue by BOKE2014** [pipipi-pikachu/PPTist#137]
设备：MacBook Air macOS Big Sur 11.6.8
浏览器：
1、Safari：点击“文件”—— “打印/导出PDF”—— 弹出窗口点击“打印/导出PDF”无响应 
2、Chrome： 点击 “保存PDF”后始终处于“保存正在保存..."

谢谢！

**Comment by pipipi-pikachu** [comment]
Chrome下无法复现

**Comment by BOKE2014** [comment]
> Chrome下无法复现

https://user-images.githubusercontent.com/35056286/183865576-5390f494-ddc6-4b3e-b6b0-bca0bf7ce77d.mov

**Comment by BOKE2014** [comment]
> Chrome下无法复现

在Edge上可以打印，但保存PDF实际上也是没有响应的

**Comment by pipipi-pikachu** [comment]
无法复现，建议你先尝试：
1 不经过应用，直接调用浏览器打印看是否正常可用
2 查看是否有报错信息
3 拉取代码，在开发环境下调试查看是否有报错信息
