### ISSUE TITLE
[Bug report] yarn方式安装后 项目无法运行

### ISSUE THREAD

**Issue by HengCC** [pipipi-pikachu/PPTist#139]
项目拉下来后. 如果不通过npm安装. 通过yarn安装的话. 会报错.  无论是build还是serve.   通过npm安装没有问题.
项目中存在package-lock.json文件. 是否是某些库锁了版本. 
错误提示如下:`Argument of type 'readonly Mark[]' is not assignable to parameter of type 'Mark[]'.`

**Comment by pipipi-pikachu** [comment]
当然，请保证 package-lock.json 能够正常工作。

如需使用 yarn 、pnpm 等工具，请通过外部手段将 package-lock.json 转换为对应的 lock 文件，或者根据报错处理依赖的版本差异
