### ISSUE TITLE
Safari 在圖片儲存時會位移

### ISSUE THREAD

**Issue by EvanLyu** [pipipi-pikachu/PPTist#140]
編輯器畫面
![截圖 2022-08-22 上午2 57 35](https://user-images.githubusercontent.com/6142091/185806739-d8547628-bcda-4c80-940f-d59c3cb516af.png)

儲存結果
![blob_b7392ded0e](https://user-images.githubusercontent.com/6142091/185806746-1af65164-7db4-46f8-aaf8-b47af296efb6.png)

1. 系统环境(Mac or Windows)：Mac
2. 浏览器环境(如：Chrome v89.0.4389.114)：Safari 15.5

**Comment by pipipi-pikachu** [comment]
计划开源版本后续不会做safari相关兼容工作了。
