### ISSUE TITLE
[Bug report] 竖状文本框存在多行时，旋转效果异常

### ISSUE THREAD

**Issue by 948764321** [pipipi-pikachu/PPTist#143]
**问题描述**  
1. 问题触发的条件/操作流程
新建竖状文本框->输入多行文本->旋转文本框
![image](https://user-images.githubusercontent.com/74353117/186086588-74bade36-b444-4eb0-86a2-0bb2c9f6b755.png)
即可发现文字与操作框不在一起了

**环境信息**  
如有必要，可包含以下部分：
1. 系统环境： Windows 10
2. 浏览器环境：Chrome Edge

**Comment by 948764321** [comment]
相关修改 #144 ，还望大佬 merge

**Comment by pipipi-pikachu** [comment]
> 相关修改 #144 ，还望大佬 merge

👍
