### ISSUE TITLE
求：如何将这个项目作为一个组件在自己的项目中引入呀

### ISSUE THREAD

**Issue by huangyuanyin** [pipipi-pikachu/PPTist#145]
**注意**
1. 请在提交前仔细阅读 README 中的后续规划部分，不要重复提交已经在规划中的请求。
2. 请完整地描述你需要的功能及场景。

**Comment by pipipi-pikachu** [comment]
本项目不支持作为第三方引入，短期内也没有相关计划（具体可见 #67）。
建议直接基于此项目构建，或是手动合并到你的项目中。
