### ISSUE TITLE
动态插入表格

### ISSUE THREAD

**Issue by ChineseYulong** [pipipi-pikachu/PPTist#146]
动态添加表格数据，数据如何动态添加在创建的单元格呢？

**Comment by pipipi-pikachu** [comment]
动态是指什么？

**Comment by ChineseYulong** [comment]
菜单栏有一个数据导入的功能，然后以表格形式将数据展示在ppt中，表头和内容的数据如何动态将数据插入在表格单元格中
![屏幕截图 2022-08-31 203706](https://user-images.githubusercontent.com/50763995/187680371-4be6b852-eb17-4040-a8e8-87e40437d40b.png)

**Comment by pipipi-pikachu** [comment]
就是插入带数据的表格？

看表格元素的数据结构：https://github.com/pipipi-pikachu/PPTist/blob/master/doc/DirectoryAndData.md

根据上面的结构自行构建你据要的表格数据，然后参考https://github.com/pipipi-pikachu/PPTist/blob/master/src/hooks/useCreateElement.ts 中的createTableElement 实现插入方法

**Comment by ChineseYulong** [comment]
上方图片就是按照这个方法写的，但是出来的效果和预想的不太一样，不理解他如何将data渲染上去的

**Comment by pipipi-pikachu** [comment]
```ts
const data = [...]
slidesStore.addElement({
      type: 'table',
      data,
      ...
})
```
本质上就是这样啊，
如果插入结果不正确，检查一下你的data是否构建正确，

你也可以直接拿一个现成的data来测试：
![image](https://user-images.githubusercontent.com/22936489/187728620-9715aa2d-ea67-4115-adb6-da32173b5dbe.png)
