### ISSUE TITLE
大佬，文本框、线条、图形这些元素的渲染是啥原理啊？完全没看懂呢

### ISSUE THREAD

**Issue by Yekaiii** [pipipi-pikachu/PPTist#147]
**注意**
1. 请在提交前仔细阅读 README 中的后续规划部分，不要重复提交已经在规划中的请求。
2. 请完整地描述你需要的功能及场景。

**Comment by pipipi-pikachu** [comment]
本项目是采用最简单的基于dom的渲染方案哈，能理解现代mv*框架的应该就能理解这些数据是如何渲染到视图上的，你也可以看看这些：https://github.com/pipipi-pikachu/PPTist/tree/master/doc

**Comment by Yekaiii** [comment]
好的，感谢您的回复
