### ISSUE TITLE
有什么办法可以做到导入pptx的功能？

### ISSUE THREAD

**Issue by KangKang0928** [pipipi-pikachu/PPTist#150]
**注意**
1. 请在提交前仔细阅读 README 中的后续规划部分，不要重复提交已经在规划中的请求。
2. 请完整地描述你需要的功能及场景。

**Comment by pipipi-pikachu** [comment]
pptx -> json -> pptist

见 README [常见问题](https://github.com/pipipi-pikachu/PPTist/blob/master/doc/Q&A.md)

**Comment by KangKang0928** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
