### ISSUE TITLE
[Feature request]能否加个自动动画

### ISSUE THREAD

**Issue by ciciPocker** [pipipi-pikachu/PPTist#152]
目前场景动画太局限了，可以加个自定义轨迹的动画吗？

**Comment by pipipi-pikachu** [comment]
很长时间内应该不会有相关计划。
个人的看法是：作为一个幻灯片应用（而不是低代码平台），目前的动画和模式已经基本够用了，同时考虑易用性和投入产出比，如果有更多的动画需求，更建议通过丰富动画库来达到目的，而不是提供自制动画的能力。
