### ISSUE TITLE
你好，什么时候可以支持导入本地PPTX，文件

### ISSUE THREAD

**Issue by nasasky** [pipipi-pikachu/PPTist#154]
**注意**
1. 请在提交前仔细阅读 README 中的后续规划部分，不要重复提交已经在规划中的请求。
2. 请完整地描述你需要的功能及场景。

**Comment by BOKE2014** [comment]
嗯，能够导入PPTX是非常非常非常重要的功能，哪怕不是那么完美也是要有的重要功能。估计作者一直在关注这个问题。

**Comment by pipipi-pikachu** [comment]
见README和历史issues
