### ISSUE TITLE
[Feature request] 新增纵向画布尺寸

### ISSUE THREAD

**Issue by mike1936** [pipipi-pikachu/PPTist#155]
有些时候需要使用纵向画布用于生成产品小册子，并且需要支持导出.pptx格式方便负责打印的用户后续也可以通过powerpoint对页面版式进行微调

**Comment by BOKE2014** [comment]
这个功能比较重要，附议一下

**Comment by more-strive** [comment]
看下这个 https://github.com/more-strive/vue-fabric-draw
