### ISSUE TITLE
用户可以自己编辑页眉和页脚的内容吗？[Feature request]

### ISSUE THREAD

**Issue by BOKE2014** [pipipi-pikachu/PPTist#157]
**注意**
1. 请在提交前仔细阅读 README 中的后续规划部分，不要重复提交已经在规划中的请求。
2. 请完整地描述你需要的功能及场景。

**Comment by pipipi-pikachu** [comment]
页眉和页脚就是普通文本框而已，用户手动添加就行。有快捷方式需求的自行二开。

**Comment by BOKE2014** [comment]
> 

OK
