### ISSUE TITLE
[Feature request] 是否可以增加回放功能，保存画板笔记、动画等

### ISSUE THREAD

**Issue by kankanol1** [pipipi-pikachu/PPTist#166]
**注意**
1. 能够增加回放功能
     其实就是将授课中的动作记录下来。
     （另外通过其它设备录制音频，实现自动回放课件同时播放音频的视频效果）

**Comment by kankanol1** [comment]
这个没有什么思路，大家有什么思路可以提供一下，就是好多课件回放为了节省视频流量，做一些课件+画板+音频等素材组合式的视频效果，大家可以各抒己见，哪怕一个思路都万分感谢！！！

**Comment by pipipi-pikachu** [comment]
因为不属于项目计划功能，这个issue先关闭了，若需要讨论，可以在 https://github.com/pipipi-pikachu/PPTist/discussions 中发帖
