### ISSUE TITLE
[Bug report] ProsemirrorEditor导致浏览器崩溃

### ISSUE THREAD

**Issue by ciciPocker** [pipipi-pikachu/PPTist#167]
**问题描述**  
请尽量简洁、完整地描述你遇到的bug，至少包括以下部分（如有必要，可提供截图甚至视频）：
1. ProsemirrorEditor在输入中文的时候很容易导致浏览器崩溃，用Vue.js devtools 发现输入中文的时候每秒都会发送不下20个事件，请问下有什么好建议吗？

**环境信息**  
如有必要，可包含以下部分：
1. 系统环境(Mac)
2. 浏览器环境(如：Chrome)

**Comment by pipipi-pikachu** [comment]
浏览器崩溃是在本地开发环境下吗？在线上demo未测出过卡顿或崩溃的情况。
如果是开发环境，确实会出现性能问题，但并不仅限于富文本编辑，只要打开Vue devtools开发一段时间后都会导致页面卡顿，我没有深入研究过这块，不确定是否是Vue devtools的问题。

另外你说的发送事件是指这个吗
![image](https://user-images.githubusercontent.com/22936489/202951962-e81dd4f2-39ff-4085-92a6-4d112061423a.png)
可否提供相关截图？这边测试完全正常

**Comment by ciciPocker** [comment]
component events里面是正常的，内部处理的事件很多
![image](https://user-images.githubusercontent.com/113871607/202953248-72083a80-36fc-4aa4-9b89-a6d443f85db7.png)

**Comment by ciciPocker** [comment]
component events里面是正常的，内部处理的事件很多
![image](https://user-images.githubusercontent.com/113871607/202953248-72083a80-36fc-4aa4-9b89-a6d443f85db7.png)
