### ISSUE TITLE
[Bug report] 无法插入文字

### ISSUE THREAD

**Issue by BluePacificOcean** [pipipi-pikachu/PPTist#169]
**注意**
1. 请在提问前先尝试搜索历史 Issue 记录，避免重复的问题。
2. 请确保提问时已经仔细阅读过 README 中的相关事项。
3. 过于随意的 Issue 可能会被直接关闭（表述不清楚、信息不完整、无复现方法）

**问题描述**  
请尽量简洁、完整地描述你遇到的bug，至少包括以下部分（如有必要，可提供截图甚至视频）：
1. 问题触发的条件/操作流程
偶然发生，点击插入文字然后输入文字 视频如链接: https://pan.baidu.com/s/1329z2xKF4GZutWzeO0a5OQ 提取码: 4hed
3. 期望表现与实际表现
期望表现：点击插入文字然后输入文字后显示文字框
实际表现：点击插入文字然后输入文字后不显示文字框
**环境信息**  
如有必要，可包含以下部分：
1. 系统环境(Mac or Windows) win10 21h2
2. 浏览器环境(如：Chrome v89.0.4389.114) edge v107.0.1418.62 和 chrome v108.0.5359.95
3. 如拉取后无法运行，请提供相关异常指向的依赖及其版本信息

**Comment by pipipi-pikachu** [comment]
这是因为失焦检查空文本框时，编辑器的值还未传入（因为做了防抖有延迟），现已修复。

**Comment by TaiPinYoung** [comment]
好的，学习了
