### ISSUE TITLE
[Feature request]  请问未来会支持多人协同编辑吗？

### ISSUE THREAD

**Issue by JackFrancisLiu** [pipipi-pikachu/PPTist#172]
请问未来会支持多人协同编辑吗？
以后会实现类似腾讯协同ppt的功能吗？

**Comment by pipipi-pikachu** [comment]
有基于 [yjs](https://github.com/yjs/yjs) 去支持协同编辑的想法，但目前还没有做具体的调研

**Comment by pipipi-pikachu** [comment]
计划开源版本不会实现/提供该功能。
