### ISSUE TITLE
[Bug report] await db.snapshots.bulkDelete(needDeleteKeys) 这里有一个报错

### ISSUE THREAD

**Issue by shiqwang** [pipipi-pikachu/PPTist#173]
ERROR in src/store/snapshot.ts:86:37
TS2345: Argument of type 'IndexableTypeArray' is not assignable to parameter of type 'number[]'.
  Type 'IndexableTypePart' is not assignable to type 'number'.
    Type 'string' is not assignable to type 'number'.
    84 |       }
    85 |
  > 86 |       await db.snapshots.bulkDelete(needDeleteKeys)
       |                                     ^^^^^^^^^^^^^^
    87 |
    88 |       this.setSnapshotCursor(snapshotLength - 1)
    89 |       this.setSnapshotLength(snapshotLength)

**Comment by pipipi-pikachu** [comment]
这是 dexie 版本不兼容导致的，你可以检查一下自己 node_modules 中 dexie 的版本是否与仓库的一致（3.0.3）
