### ISSUE TITLE
请问导入PPT的功能计划会在什么时候实现呢？[Feature request]

### ISSUE THREAD

**Issue by zwgdrs** [pipipi-pikachu/PPTist#177]
如题

**Comment by BOKE2014** [comment]
这个可以说非常重要

**Comment by pipipi-pikachu** [comment]
可能会在不久后发布一个基于 https://github.com/pipipi-pikachu/pptx2json 实现的带有导入demo的版本。
但是注意，这仅仅是一个demo，完全没法用于生产环境。发布这个版本只是给有需要的开发者提供一个思路/案例，仅此而已。

如果问我什么时候能够上线一个完整的导入功能，很抱歉，我不知道，因为这取决于 pptx2json  的完善程度，或者社区出现了更好的工具。
