### ISSUE TITLE
[Bug report]npm install安装报错

### ISSUE THREAD

**Issue by gogo1008** [pipipi-pikachu/PPTist#180]
**问题描述**  

![image](https://user-images.githubusercontent.com/36293698/223293224-cb71d648-af4e-4473-8949-853bc56ac3f0.png)

npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated rollup-plugin-terser@7.0.2: This package 
has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm ERR! Cannot read properties of null (reading 'pickAlgorithm')

npm ERR! A complete log of this run can be found in:

**环境信息**  
如有必要，可包含以下部分：
1. 系统环境(Windows 2010)

**Comment by pipipi-pikachu** [comment]
你本地环境的问题。参考：
https://stackoverflow.com/questions/70019872/npm-err-cannot-read-properties-of-null-reading-pickalgorithm/70536556

**Comment by gogo1008** [comment]
已解决：清除缓存后再安装  npm cache clear --force
