### ISSUE TITLE
[Bug report]自定义元素iframe插入后，左侧缩略图无显示、演示时无法显示

### ISSUE THREAD

**Issue by shixiangkuangmo** [pipipi-pikachu/PPTist#183]
**自定义元素iframe插入后，左侧缩略图无显示、演示时无法显示**
win10  Chrome 版本 110.0.5481.180
![1](https://user-images.githubusercontent.com/31498452/224639947-55b8ab38-3922-4d0f-b1c7-1ec2757a2660.gif)

**Comment by pipipi-pikachu** [comment]
这不是仓库内的代码，因此我这边无法判断你写的代码存在什么问题，我只能建议你自行检查相关组件是否正常渲染再进一步调试。

另外仓库分支有相同的案例可供参考。https://github.com/pipipi-pikachu/PPTist/tree/document-demo
