### ISSUE TITLE
[Bug report]document-demo分支，插入网页后，开始演示后无法操作iframe内的东西

### ISSUE THREAD

**Issue by shixiangkuangmo** [pipipi-pikachu/PPTist#184]
环境：win10   Chrome 版本 110.0.5481.180
**1.嵌入的网页中是一个视频**
[图片](https://s1.yesimg.com/2023/03/14/b483b05c3f6a3.gif)

**2.嵌入的是普通网页**
![2](https://user-images.githubusercontent.com/31498452/224871194-f19e9a47-c151-4c79-943c-e18c8f4f9c68.gif)

演示时，无法对插入的iframe中的元素进行点击、滚动等操作。

**Comment by pipipi-pikachu** [comment]
demo中的播放和缩略图是同一个组件，用一个mask挡住了，你可以重新做一个播放界面使用的组件，不要mask，也可以自己定义props传参决定是否显示mask
![image](https://user-images.githubusercontent.com/22936489/224881507-4c26c128-f686-46b6-a1f0-ab9d8dcdd342.png)

**Comment by shixiangkuangmo** [comment]
> 

好的 明白了 谢谢

**Comment by shixiangkuangmo** [comment]
> demo中的播放和缩略图是同一个组件，用一个mask挡住了，你可以重新做一个播放界面使用的组件，不要mask，也可以自己定义props传参决定是否显示mask ![image](https://user-images.githubusercontent.com/22936489/224881507-4c26c128-f686-46b6-a1f0-ab9d8dcdd342.png)

还有一个疑问  就是iframe输入完链接 点击确定后  iframe加载新页面  然后我去点击演示   退出演示后  右侧 输入链接的输入框中 之前输入的消失了

**Comment by pipipi-pikachu** [comment]
这些都是业务逻辑的问题，把绑定的数据回填到输入框不就可以了么
