### ISSUE TITLE
文字方塊調整字體大小後，回車換行字體大小能否維持

### ISSUE THREAD

**Issue by BartCheng** [pipipi-pikachu/PPTist#185]
文字方塊調整字體大小後，回車換行字體大小能否維持

問題：
目前與到狀況是我在第一行輸入文字並調整到72px，
回車換行會回到預設文字大小，
我想要保持相同大小 72px到下一行，
是否有解決方式

**Comment by pipipi-pikachu** [comment]
现在就是这样的，如果表现异常可以提供复现方法或者视频/截图

**Comment by BartCheng** [comment]
> 现在就是这样的，如果表现异常可以提供复现方法或者视频/截图

我更新套件後正常了
謝謝
