### ISSUE TITLE
[Bug report] 放映时，mousewheel 翻页事件会执行两次（Mac）

### ISSUE THREAD

**Issue by xiaoping6688** [pipipi-pikachu/PPTist#187]
如题，Mac上是这样 不知道Win上是几次。
另外就是当页面上有滚动内容，这时不应该再响应翻页而是内滚动，可通过 stopPropagation 解决~

**Comment by pipipi-pikachu** [comment]
我手上没有Mac的开发机器...后面有时间再弄一台来看看。
不过我临时用别人的Mac试了下，翻页貌似是正常的（每次滚动只翻一页）。所以你那边是在调试下发现的 mousewheel 会执行两次吗？

**Comment by xiaoping6688** [comment]
> 我手上没有Mac的开发机器...后面有时间再弄一台来看看。 不过我临时用别人的Mac试了下，翻页貌似是正常的（每次滚动只翻一页）。所以你那边是在调试下发现的 mousewheel 会执行两次吗？

嗯，必现，用的官方https://pipipi-pikachu.github.io/PPTist/测试预览功能，我是 Mac Air M1芯片最新系统，用触摸板会触发两次滚动事件，我暂时把e.deltaY < 4的不响应就稍微好点了
