### ISSUE TITLE
[Feature request]请问如何修改模板呢？

### ISSUE THREAD

**Issue by shixiangkuangmo** [pipipi-pikachu/PPTist#188]
**注意**
1. 像替换原本的模板，请问怎么将改好的模板替换进去呢？

**Comment by xiaoping6688** [comment]
> **注意**
> 
> 1. 像替换原本的模板，请问怎么将改好的模板替换进去呢？

不看代码吗？在mocks里面

**Comment by shixiangkuangmo** [comment]
> 同上。
> 
> 另外你不应该考虑如何替代原有的模板，因为数据应该来自服务端

是的 目前已改为 保存到数据库 并从数据库读取，感谢指点~
![1](https://user-images.githubusercontent.com/31498452/228179953-43a4e264-bd17-4511-95c7-b64a95341d50.jpg)

**Comment by liaoOyao** [comment]
（有偿）最后就是我们公司的业务要求我一定要和pptsist交互：
可以提供一些帮助吗，我感觉我很菜。
1、如果可以并且麻烦，有偿，请帮我改一下，支持我做二次开发， 
2、具体业务是：通过下拉列表筛选某几个维度，然后将数据库里面存的ppt的数据传给pptist 
3、最后，我强烈建议你参考一个开源组件luckysheet的写法，下面我给你推荐开发文档链接：https://mengshukeji.gitee.io/LuckysheetDocs/zh/guide/
我非常希望pptist
也能做到这么好，
方便二次开发。

**Comment by shixiangkuangmo** [comment]
> （有偿）最后就是我们公司的业务要求我一定要和pptsist交互： 可以提供一些帮助吗，我感觉我很菜。 1、如果可以并且麻烦，有偿，请帮我改一下，支持我做二次开发， 2、具体业务是：通过下拉列表筛选某几个维度，然后将数据库里面存的ppt的数据传给pptist 3、最后，我强烈建议你参考一个开源组件luckysheet的写法，下面我给你推荐开发文档链接：https://mengshukeji.gitee.io/LuckysheetDocs/zh/guide/ 我非常希望pptist 也能做到这么好， 方便二次开发。

可以  不过目前我们公司已经放弃使用这个了  我也没再深入研究了
