### ISSUE TITLE
考虑添加文件至.gitignore？

### ISSUE THREAD

**Issue by Jibacat** [pipipi-pikachu/PPTist#19]
建议将dist和package-lock.json添加至.gitignore，避免不必要的冲突。

**Comment by Jibacat** [comment]
我fork的代码，每次合并你的仓库的master分支至我的fork仓库，这俩文件都各种冲突😂

**Comment by lhyUnited** [comment]
不太合适吧，package-lock.json得有啊，要不然版本不就乱套了吗。。
dist中的产物应该是作者部署到github pages的静态页面，所以也得带上吧。

**Comment by Jibacat** [comment]
> 不太合适吧，package-lock.json得有啊，要不然版本不就乱套了吗。。
> dist中的产物应该是作者部署到github pages的静态页面，所以也得带上吧。

package-lock.json的作用我一直不是很理解，当我执行npm install后，npm不会install from package-lock.json，而是会install from package.json，并将本次安装的各个package的版本号rewrite package-lock.json文件，这使得这个文件不能起到版本锁定的功能？？
github pages的问题，可以在master分支将dist文件untrack并添加至.gitignore，然后在gh-pages分支保持dist为tracked file。

**Comment by lhyUnited** [comment]
> package-lock.json 会固化当前安装的每个软件包的版本，当运行 npm install时，npm 会使用这些确切的版本。

[http://nodejs.cn/learn/the-package-lock-json-file](http://nodejs.cn/learn/the-package-lock-json-file)

dist文件夹只是我的猜想，不做讨论了。

**Comment by pipipi-pikachu** [comment]
> > 不太合适吧，package-lock.json得有啊，要不然版本不就乱套了吗。。
> > dist中的产物应该是作者部署到github pages的静态页面，所以也得带上吧。
> 
> package-lock.json的作用我一直不是很理解，当我执行npm install后，npm不会install from package-lock.json，而是会install from package.json，并将本次安装的各个package的版本号rewrite package-lock.json文件，这使得这个文件不能起到版本锁定的功能？？
> github pages的问题，可以在master分支将dist文件untrack并添加至.gitignore，然后在gh-pages分支保持dist为tracked file。

目前dist目录主要是用在国内镜像同步，github page是在gh-pages，但gitee page上是master上的，这个可以考虑统一换到gh-pages分支即可，问题不大。

至于package-lock.json，楼上说的没错，这个是必须的，package.json中的版本号是不能锁定版本的，具体可以了解一下版本号中~和^的用法~

另外，目前package-lock.json文件可能时不时会有一些无意义的变动，原因是我几个地方的工作电脑环境有些差异，后面会尝试统一一下避免无意义的改动😃

**Comment by Jibacat** [comment]
@pipipi-pikachu @lhyUnited 
「package-lock.json 会固化当前安装的每个软件包的版本，当运行 npm install时，npm 会使用这些确切的版本。」
npm已经不是这个特性了，具体可以看一下这个链接关于这个问题的讨论。😃
https://stackoverflow.com/questions/45022048/why-does-npm-install-rewrite-package-lock-json

**Comment by pipipi-pikachu** [comment]
> @pipipi-pikachu @lhyUnited
> 「package-lock.json 会固化当前安装的每个软件包的版本，当运行 npm install时，npm 会使用这些确切的版本。」
> npm已经不是这个特性了，具体可以看一下这个链接关于这个问题的讨论。😃
> https://stackoverflow.com/questions/45022048/why-does-npm-install-rewrite-package-lock-json

注意看这个问题讨论下最高赞补充的那个issue，问题已经修复了。
npm5.0
npm5.1
npm5.4.2
这三个版本关于lock文件的处理是不同的，在最新的版本中，只有package-lock.json中的版本和package.json中的版本不兼容时（例如package.json版本为~2.0，package-lock.json版本为1.0），才会以package.json为准并改写package-lock.json，否则还是以package-lock.json为准。
英文水平有限，不确定理解是否有误，晚点我可以做个测试。
如果理解的不错，那么npm5.4.2及以上的版本中，lock文件应该是符合预期行为的。

**Comment by pipipi-pikachu** [comment]
目前已将dist添加到.gitignore，package-lock.json会继续保留
