### ISSUE TITLE
提问：使用 transform 进行画布元素的定位

### ISSUE THREAD

**Issue by 948764321** [pipipi-pikachu/PPTist#198]
背景：
  单页面节点数量过多时，拖拽画布元素会卡顿。
分析：
  大概看了看，发现项目中画布元素采用的是绝对定位使用 top、left 的方案，会导致重排

因此，想请教一下为什么不使用 transform 对画布节点进行定位呢？是有什么顾虑吗？

**Comment by pipipi-pikachu** [comment]
我也不清楚用transform会不会有什么问题，但是最开始使用left、top定位仅仅是因为实现更方便
