### ISSUE TITLE
feature: 全局快捷键支持command

### ISSUE THREAD

**Issue by lhyUnited** [pipipi-pikachu/PPTist#20]
https://github.com/pipipi-pikachu/PPTist/blob/5890ca16e63d5627e2c37d8a46f3f8e864ad8a30/src/hooks/useGlobalHotkey.ts#L138

https://github.com/pipipi-pikachu/PPTist/blob/5890ca16e63d5627e2c37d8a46f3f8e864ad8a30/src/hooks/useGlobalHotkey.ts#L143

**Comment by lhyUnited** [comment]
不确定你后面是不是漏掉了metaKey🤔

**Comment by pipipi-pikachu** [comment]
> 不确定你后面是不是漏掉了metaKey🤔

倒不是漏掉，事实上我很少使用mac😂现在手头也没有.....所以不是很清楚command和ctrl是否完全通用，所以当初只在复制的快捷键上做了兼容，目前暂时先这样以二者通用来对待吧
