### ISSUE TITLE
我建议参考aspose-slides，该库是一个后端库支持多种语言，他还原了99%的PowerPoint操作。

### ISSUE THREAD

**Issue by Hellofffff** [pipipi-pikachu/PPTist#202]
解析PPT本质上就是解析OpenXml，将PPT文件后缀改为zip就能得到ppt本质上的所有xml以及文件，建议作者可以去参考一下aspose-slides库，虽然是商业项目但是可以学习其所有方法，该库可以申请试用，也可以破解仅用于学习。

**Comment by pipipi-pikachu** [comment]
可以看看置顶issue中提到的我的另一个仓库。
拿到xml数据不难，真正的难点在于解析xml这件事的工作量很大，各种边界条件特殊情况非常多。我有时间了会一点点完善（我今年实在太忙了），也欢迎各位加入进来。
