### ISSUE TITLE
能否考虑添加一个功能：在全屏演示的右键添加 “循环放映”

### ISSUE THREAD

**Issue by zrtzrtzrtzrtzrt** [pipipi-pikachu/PPTist#208]
能否考虑添加一个功能：在全屏演示的右键添加 “循环放映”

**Comment by pipipi-pikachu** [comment]
是指播放到最后一页后继续翻页会回到第一页吗？

感觉是个很简单但有用的功能。不过估计要等到下个大版本后更新了（目前在迁移到vite生态，typescript5等），不过当前进度缓慢，因为我今年实在太忙了…

**Comment by zrtzrtzrtzrtzrt** [comment]
好的，还希望能在页面演示时 增加可选择的页面停留时长

**Comment by missile-xuan** [comment]
> 是指播放到最后一页后继续翻页会回到第一页吗？
> 
> 感觉是个很简单但有用的功能。不过估计要等到下个大版本后更新了（目前在迁移到vite生态，typescript5等），不过当前进度缓慢，因为我今年实在太忙了...

迁移vite有拎出来项目或者分支嘛？  感觉我可以帮帮忙

**Comment by pipipi-pikachu** [comment]
循环放映已更新

**Comment by pipipi-pikachu** [comment]
> > 是指播放到最后一页后继续翻页会回到第一页吗？
> > 感觉是个很简单但有用的功能。不过估计要等到下个大版本后更新了（目前在迁移到vite生态，typescript5等），不过当前进度缓慢，因为我今年实在太忙了...
> 
> 迁移vite有拎出来项目或者分支嘛？ 感觉我可以帮帮忙

目前还没有，暂时只做了迁移vite之前的一些工作，包括升级UI库、升级Vue3.3、更新TSLint/StyleLint，方便更平滑迁移，预计这批更新差不多稳定后会开新分支
