### ISSUE TITLE
[Bug report]Firefox浏览器插入表格后无法编辑

### ISSUE THREAD

**Issue by lefex** [pipipi-pikachu/PPTist#209]
**注意**
1. 请在提问前先尝试搜索历史 Issue 记录，避免重复的问题。
2. 请确保提问时已经仔细阅读过 README 中的相关事项。
3. 过于随意的 Issue 可能会被直接关闭（表述不清楚、信息不完整、无复现方法）

**问题描述**  
请尽量简洁、完整地描述你遇到的bug，至少包括以下部分（如有必要，可提供截图甚至视频）：

插入表格后，无法输入内容：
![image](https://github.com/pipipi-pikachu/PPTist/assets/8437666/31c17eda-f312-4c01-aca6-5e107b3f3f35)

**环境信息**  
如有必要，可包含以下部分：
1. 系统环境(Mac or Windows) Mac
3. 浏览器环境(如：Chrome v89.0.4389.114) Firefox109.0.1
4. 如拉取后无法运行，请提供相关异常指向的依赖及其版本信息

**Comment by pipipi-pikachu** [comment]
本质是 FireFox 不支持 contenteditable="plaintext-only" 导致的，目前仅做了临时处理，计划最终要把单元格也做成支持富文本才行才行😕
