### ISSUE TITLE
导出PPTX文件，视频无法保存在ppt里

### ISSUE THREAD

**Issue by wxw68** [pipipi-pikachu/PPTist#219]
**问题描述**  
请尽量简洁、完整地描述你遇到的bug，至少包括以下部分（如有必要，可提供截图甚至视频）：
1.导出PPTX文件，视频无法保存在ppt里,只能在浏览器上的时候才能显示视频，开始以为是网络地址访问不到修改成了本地视频依然不行

**环境信息**  
如有必要，可包含以下部分：
1. 系统环境(Mac or Windows)。
     window10
3. 浏览器环境(如：Chrome v89.0.4389.114)。
   Chrome  `112.0.5615.138（正式版本）

**Comment by wxw68** [comment]
` const videoChange = (event:Event) => {
      const currentTarget = event.target as HTMLInputElement
      const files = currentTarget.files
      if (files !== null) {
        if (files[0].size > 10 * 1024 * 1024) { // 设置视频大小不得超过多少M
          message.error('视频不能超过10MB')
          return
        }
        else {
          videoSrc.value = window.URL.createObjectURL(files[0])
        }
      }`
从本地读取视频，可以展示也不能保存

**Comment by pipipi-pikachu** [comment]
这不是一个Bug，而是原本就不支持导出音视频媒体，虽然我还是在新版中添加了是否将音视频包含在导出结果的选项，但我需要提醒一下，这个功能实际在生产环境中是有问题的（这也是我原本没有做的原因）：

1. 导出耗时会极大幅度变长，如果视频比较大，估计没有多少人愿意等那么久；
2. 该功能受限于视频的格式，而我并不确定使用者在生产环境中会如何使用插入视频功能，举例来说很多这种视频资源在正式的项目中都会使用HLS，而这种格式在现有方案下是没法导出的，也许可以保存两份文件（一份mp4、一份m3u8切片），但这都不是统一的标准，所以我不想做一个demo中看起来OK但实际估计用不上的功能。
