### ISSUE TITLE
[Bug report] 插入形状修改颜色填充渐变色选择颜色时会卡死

### ISSUE THREAD

**Issue by zengyilun** [pipipi-pikachu/PPTist#220]
问题描述
请尽量简洁、完整地描述你遇到的bug，至少包括以下部分（如有必要，可提供截图甚至视频）：
1.选择插入形状，随便选择一个图形,在右边样式tab中纯色填充修改为渐变填充，选择起点颜色后点击终点颜色ppt页面卡死

环境信息
如有必要，可包含以下部分：

系统环境(Mac or Windows)。
window10
浏览器环境(如：Chrome v89.0.4389.114)。
Chrome 116.0.5845.111（正式版本） （64 位）

**Comment by zengyilun** [comment]
![ppt卡死截图](https://github.com/pipipi-pikachu/PPTist/assets/58414094/e2c90eef-0768-45b7-8346-54986fc12127)

**Comment by pipipi-pikachu** [comment]
当然在移除antdv之前，我也会先发布一个临时处理的新版本，不过如上文所说，这并不可靠。
