### ISSUE TITLE
想问一下上传音视频不能上传本地的音视频吗[Feature request]

### ISSUE THREAD

**Issue by zrtzrtzrtzrtzrt** [pipipi-pikachu/PPTist#222]
试了一下上传音视频，不能上传本地的音视频，只能输入http开头的地址

**Comment by pipipi-pikachu** [comment]
https://github.com/pipipi-pikachu/PPTist/blob/master/doc/Q&A.md#q-%E5%85%B6%E4%BB%96

拉下代码简单修改几行代码就可以实现了，Demo是纯前端的，没法支持本地上传
