### ISSUE TITLE
用Micro-App集成后出现幻灯片位置错误

### ISSUE THREAD

**Issue by jackyshenai** [pipipi-pikachu/PPTist#225]
**问题描述**  
使用京东的Micro-App作为子应用集成后，出现了位置错误：
1、由于顶部多了一个Navbar，幻灯片页面出现了向下偏移，如下图所示：
![image](https://github.com/pipipi-pikachu/PPTist/assets/137123926/ba3c6474-b320-4275-b498-8931c50bfcf3)
2、选中页面元素，出现大小与位置错乱，如下图所示
![image](https://github.com/pipipi-pikachu/PPTist/assets/137123926/244e2090-cc0c-4f20-bead-19fbc8dee37b)
3、幻灯片放映出现空白
![image](https://github.com/pipipi-pikachu/PPTist/assets/137123926/bcde50de-b2bc-4d10-939c-d8b4fa012656)

**环境信息**  
1、Windows，Edge浏览器，117.0.5938.152（正式版本） （64 位）

**Comment by pipipi-pikachu** [comment]
这很明显是微前端框架需要解决的问题，你应该到micro-app的仓库下请求帮助……我并不熟悉这个框架
