### ISSUE TITLE
[Feature request]查找（Ctrl+F）功能优化——支持像VSCODE类似的查找功能（针对英文）

### ISSUE THREAD

**Issue by AcWrong02** [pipipi-pikachu/PPTist#231]
目前的模式对于英文是直接区分大小写进行查询
![image](https://github.com/pipipi-pikachu/PPTist/assets/147061401/117e46f4-cb15-4549-b43b-eaa3b9483d44)
是否可以对英文查找支持三种模式：不区分大小写、只查看大写、只查看小写
![image](https://github.com/pipipi-pikachu/PPTist/assets/147061401/143049a9-1317-4575-a7cd-e3d6fdbc414f)

**Comment by pipipi-pikachu** [comment]
添加了是否忽略大小写的开关，
没有实现【只查看大写】、【只查看小写】，个人觉得意义不大，正常搜索配合关闭忽略大小写就可以做到同样的效果，有需要可自行实现
