### ISSUE TITLE
[Bug report] 导入PPTX直接报错了

### ISSUE THREAD

**Issue by andersonyali** [pipipi-pikachu/PPTist#232]
最新导入pptx会出错
![image](https://github.com/pipipi-pikachu/PPTist/assets/19464762/64c28440-d5b8-45d5-a166-0fc6609dcc76)

**Comment by pipipi-pikachu** [comment]
更新下 [pptx2json](https://github.com/pipipi-pikachu/pptx2json) 的版本

另外看下置顶 issue ，导入相关问题在另一个仓库处理
