### ISSUE TITLE
形状支持自定义绘制曲线，动画支持自定义绘制曲线或直线路径

### ISSUE THREAD

**Issue by keepmovng** [pipipi-pikachu/PPTist#234]
形状支持自定义绘制曲线，动画支持自定义绘制曲线或直线路径

**Comment by keepmovng** [comment]
您好！
形状支持自定义绘制曲线，动画支持自定义绘制曲线或直线路径。
这两个需求可以支持吗？

**Comment by pipipi-pikachu** [comment]
自定义绘制多边形中添加了自定义绘制曲线（鼠标按住不放绘制，非封闭状态下回车确认）。

目前暂时没有计划实现路径动画
