### ISSUE TITLE
[Feature request]有没有办法做成一个与chatgpt结合的ppt生成工具？提出需求，生成md后发回修改，修改确定后生成ppt

### ISSUE THREAD

**Issue by fattank** [pipipi-pikachu/PPTist#241]
**注意**
1. 请在提问前先尝试搜索历史 Issue 记录，避免重复的问题。
2. 请在提交前仔细阅读 README 中的后续规划部分，不要重复提交已经在规划中的请求。
3. 请完整地描述你需要的功能及场景。
4. 本项目是一个“在线幻灯片应用/在线演示工具”，请注意你的需求是否符合该项目的定位，如不符合将不予接受（例如你的需求针对的是：图片编辑器、低代码编辑器、在线设计软件等，请自行实现）。

**Comment by pipipi-pikachu** [comment]
只要准备好AI接口，这没什么难点吧，本项目数据是json格式，md与json互转的库应该也非常多。

但本仓库本身目前不会去做这些涉及服务端的功能，具体原因在Q&A已经说过了。
