### ISSUE TITLE
获取导入的PPTX文件中的母版数据

### ISSUE THREAD

**Issue by DominicHan** [pipipi-pikachu/PPTist#244]
目前导入的pptx中母版的内容展示不出来，这部分数据我可以通过改造pptxtojson.js得到吗？

**Comment by pipipi-pikachu** [comment]
可以，你可以参考pptx.js这个库的实现，它将母版的内容转成了一个个分散的元素，但也存在两个问题：1、母版转出的形状和实际有差异，看着像是比例有异常；2、转出母版内的形状的同时，里面的一些占位符也会跟着一起被解析出来，需要你自己解决。

其他疑问和讨论可以移步到pptxtojson的issue区
