### ISSUE TITLE
组件化并支持发布npm引用

### ISSUE THREAD

**Issue by ijry** [pipipi-pikachu/PPTist#247]
**注意**
目前项目是一个完整的Vue3项目，可以看到功能的实现已经是相对组件化了，但在实际用户使用中，很多场景是希望引入到自己的项目中，这存在较大的引用工作量与文件隔离污染，建议将组件进一步封装在一个独立的组件文件夹内，最终实现：
```
<template>
    <pptist v-model="jsonData"></pptist>
</template>
...
<script setup>
imort { ref } from 'vue'
import pptist from 'pptist'
const jsonData = ref({})

```

**Comment by pipipi-pikachu** [comment]
暂无此计划，具体见：https://github.com/pipipi-pikachu/PPTist/blob/master/doc/Q&A.md#q-%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%8D%E6%98%AFnpm%E5%8C%85
