### ISSUE TITLE
导出PDF

### ISSUE THREAD

**Issue by bestNiu** [pipipi-pikachu/PPTist#248]
1、看到作者 文档必读有一块是关于PDF的生成是非常明确见简单的

2、由于本人非前端专业，可否麻烦作者帮忙给一些关键词，或者一些库，可以简单快速的把我们的PPT X生成PDF？ 

还是说，根据各个分页的图片直接合成PDF呢？ 

能否给一些思路，谢谢

**Comment by pipipi-pikachu** [comment]
可以利用puppeteer、pdf-lib这两个库在后台生成PDF
