### ISSUE TITLE
您好，请问这个项目的导入和导出功能什么时候能够上线

### ISSUE THREAD

**Issue by xsxs89757** [pipipi-pikachu/PPTist#25]
您是否需要赞助

**Comment by JAVPHP** [comment]
同问，这个项目是否支持生成ppt

**Comment by pipipi-pikachu** [comment]
> 您是否需要赞助

首先感谢关注。
这个问题我只能说，功能后面会去做，但时间上无法给出准确的答复，可以看看这里：https://github.com/pipipi-pikachu/PPTist#-todo

目前主要的问题在于：导入导出所涉及的东西，不是我目前的知识能够解决的，可能需要花时间去学习一些PPT本身和XML相关的东西（我暂时也还没有找到有用的第三方轮子）。如果有熟悉相关领域的朋友，应该可以独立实现出来，毕竟这本质上是一个PPTX文件数据与JSON相互转换的问题，和这个项目本身的联系并不大。

**Comment by xsxs89757** [comment]
明白了

**Comment by cnbizhh** [comment]
https://github.com/gitbrent/PptxGenJS
