### ISSUE TITLE
通过pptx2json获取到的json如何转化成pptist？

### ISSUE THREAD

**Issue by terranc** [pipipi-pikachu/PPTist#256]
我现在想通过 https://pipipi-pikachu.github.io/pptx2json/ 来把用户的pptx转成json，然后可能经过一些文本编辑（可能是修改其中的一些文本内容），然后再导入pptist里面来恢复可视化的编辑。不知这个方案可行与否，目前拿到的这个json不知如何变成pttist支持的导入格式

**Comment by pipipi-pikachu** [comment]
pptxtojson拿到的数据转pptist的数据，这不就是导入PPTX文件功能的内容么 https://github.com/pipipi-pikachu/PPTist/blob/master/src/hooks/useImport.ts
