### ISSUE TITLE
[Bug report]同样函数生成的base64图片，导出pptx，用office 2016打开的时候，有一张无法显示。

### ISSUE THREAD

**Issue by woscj** [pipipi-pikachu/PPTist#258]
[long_text_2024-03-17-09-56-48.json](https://github.com/pipipi-pikachu/PPTist/files/14626113/long_text_2024-03-17-09-56-48.json)

用附件的json，做导出操作，用office 2016打开的时候，有一张无法显示。想弄清楚为什么，后来尝试用最新的wps打开没有出现这个问题，
![lQLPJxEI4BkPtUnNAijNAgiwcUnQ0_e5tb4F5Wga--7kAA_520_552](https://github.com/pipipi-pikachu/PPTist/assets/24446039/aeadde3a-2e1a-4f9f-9a95-d1eed9309cd3)

![image](https://github.com/pipipi-pikachu/PPTist/assets/24446039/f922cd22-f11b-4086-98c6-ab7f4f31eb1b)

**Comment by pipipi-pikachu** [comment]
你这个情况我也不清楚，导出PPTX文件是调用的 https://gitbrent.github.io/PptxGenJS/ 这个库，你可以尝试在那儿寻求帮助。
另外我将你json中的base64在浏览器中打开再保存为文件，最后插入pptist中导出，用office 2013打开是正常的（我只有这个版本的office），你可以试试同样的办法，看看是不是base64本身的问题
