### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by missile-xuan** [pipipi-pikachu/PPTist#27]
**问题描述**  
大佬 我发现在历史快照中

导致在ppt中间某页面添加页面后  点击撤销 
当前页面选中的页面并不是添加前的光标页面

![image](https://user-images.githubusercontent.com/38873815/117957238-71056f00-b34c-11eb-88e6-15c3679769ca.png)
应该是截图中的代码的问题 store/actions.ts  ADD_SNAPSHOT中
但是没理解这段代码有什么其他特殊的用处

（给大佬递上星星）

**Comment by pipipi-pikachu** [comment]
嗯..是有这个问题，也确实是图上这段代码导致的，但是目前暂时还不能移除这段代码。
具体原因，你可以先注释这部分代码，然后这样操作：
1、先添加到至少两个页面
2、在第一页进行某些修改操作
3、切换到另一页进行某些修改操作
4、撤销
这时候会发现页面焦点回到了前一个操作的页面，但事实上应该停留在现在的页面才对。图上的代码就是在解决这个问题。

虽然目前导致了其他的问题（你所描述的现象），但是相对来说上述现象在实际场景中可能出现的更频繁，也更难以接受。因此这个问题暂时会保留，有机会再探索下更完善的方案（例如用命令式代替现在的快照式等）。

**Comment by missile-xuan** [comment]
！感谢大佬解答

又遇到个不太理解的地方
/Editor/Canvas/index.vue 文件中
![image](https://user-images.githubusercontent.com/38873815/118094312-28f45400-b401-11eb-82b0-876e3ef4f607.png)
![image](https://user-images.githubusercontent.com/38873815/118094355-34477f80-b401-11eb-99ea-1cfb44733be4.png)

activeGroupElementId  这个参数好像一直都是空字串  想问下这个是做什么用的啊？

**Comment by pipipi-pikachu** [comment]
> ！感谢大佬解答
> 
> 又遇到个不太理解的地方
> /Editor/Canvas/index.vue 文件中
> ![image](https://user-images.githubusercontent.com/38873815/118094312-28f45400-b401-11eb-82b0-876e3ef4f607.png)
> ![image](https://user-images.githubusercontent.com/38873815/118094355-34477f80-b401-11eb-99ea-1cfb44733be4.png)
> 
> activeGroupElementId 这个参数好像一直都是空字串 想问下这个是做什么用的啊？

在多选的状态下，再次连续两次点击其中的某个元素，该元素会进入可独立操作的状态。
这个ID就是标记这个元素的
