### ISSUE TITLE
[Feature request]关于默认打开 如何 打开默认 ppt

### ISSUE THREAD

**Issue by Wangzh0927** [pipipi-pikachu/PPTist#276]
大佬好，看到您项目很 nice，想作为 ppt 默认打开演示作用，不知道怎么让别人打开就显示不同的 ppt 呢

我看用的mock，如果有很多，咋整，有建议么

**Comment by pipipi-pikachu** [comment]
我没太理解你的意思，mocks只是demo演示用的虚拟数据，真实上生产必须得接服务端和数据库的呀
