### ISSUE TITLE
图片添加了边框，导出到PPTX时边框无效，显示不出来

### ISSUE THREAD

**Issue by aaronyu791202** [pipipi-pikachu/PPTist#278]
**注意**
1. 请在提问前先尝试搜索历史 Issue 记录，避免重复的问题。
2. 请确保提问时已经仔细阅读过 README 中的相关事项。
3. 过于随意的 Issue 可能会被直接关闭（无标题、无描述、表述不清楚、信息不完整、无复现方法、重复的问题等）。

**问题描述**  
请尽量简洁、完整地描述你遇到的bug，至少包括以下部分（如有必要，可提供截图甚至视频）：
1. 问题触发的条件/操作流程。
2. 期望表现与实际表现。

**环境信息**  
如有必要，可包含以下部分：
1. 系统环境(Mac or Windows)。
2. 浏览器环境(如：Chrome v89.0.4389.114)。
3. 如拉取后无法运行，请提供相关异常指向的依赖及其版本信息。

**Comment by pipipi-pikachu** [comment]
https://github.com/pipipi-pikachu/PPTist/blob/master/doc/Q%26A.md#q-%E5%85%B3%E4%BA%8E%E5%AF%BC%E5%85%A5%E5%AF%BC%E5%87%BApptx%E6%96%87%E4%BB%B6

不支持导出图片描边
