### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by FaizanKhanDev** [pipipi-pikachu/PPTist#284]
When uploading a PPTX file, the animations are completely destroyed, and the layout becomes disturbed. Please refer to the attached screenshot to see the issue.

![imported on Web](https://github.com/pipipi-pikachu/PPTist/assets/117845718/bb6eabd2-f8b4-4b14-841a-4d7a18b6a7fb)

**### After download** 
![After Downloaded](https://github.com/pipipi-pikachu/PPTist/assets/117845718/6d886fc0-fa4b-4053-ba85-a10e476881f6)

Please review this PPTX file on Canva and import it into PPTist:
[Canva PPTX File](https://www.canva.com/design/DAGKpKT1KY0/CsVqnfNYZylAxU6hGV_Mcw/edit?utm_content=DAGKpKT1KY0&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

**Comment by pipipi-pikachu** [comment]
https://github.com/pipipi-pikachu/PPTist/issues/191
