### ISSUE TITLE
文本框内的文字，样式丢失与位置错乱

### ISSUE THREAD

**Issue by rookiecdn** [pipipi-pikachu/PPTist#287]
我解析ppt后，进行了查看分析，发现在json文件中，转换的数据一切正常，但是在将content转换成html的时候，style样式却意外丢失了
![image](https://github.com/user-attachments/assets/66ab84a8-95f4-4ce7-80e0-bdb6b333ac14)
dom中的样式是这样
![image](https://github.com/user-attachments/assets/7caa9f67-0137-4739-b2b3-d8c68750a9bb)

**Comment by rookiecdn** [comment]
字体大小应该是44.9px

**Comment by pipipi-pikachu** [comment]
你注意看图中你圈出的font-size: 44px的后面，确实是有一个font-size: smaller的。

PPTist的解析没有问题，问题出在pptx转json的那边，需要把角标的font-size: smaller样式移除

**Comment by pipipi-pikachu** [comment]
后续我会在那边处理

**Comment by rookiecdn** [comment]
好的，感谢，我再详细说明一下，pptxtojson解析的数据确实已经渲染，应该是文本框的定位父元素不正确
![image](https://github.com/user-attachments/assets/d130f1b9-17c5-4ed1-9389-ebcf6234bb7b)
![image](https://github.com/user-attachments/assets/8a3d7d6c-5476-4be8-9843-cce3926bf9db)
