### ISSUE TITLE
导入pptx，背景全无，局部位置错乱

### ISSUE THREAD

**Issue by jiashaokun** [pipipi-pikachu/PPTist#288]
![1](https://github.com/user-attachments/assets/6b77c734-26a2-4a04-b1fd-c0de281e8f2f)
背景全无

![image](https://github.com/user-attachments/assets/b2c6df37-7a7d-4f73-8ecd-763c83417016)
位置错乱

**Comment by pipipi-pikachu** [comment]
#191
