### ISSUE TITLE
[Bug report] 富文本元素切换页面后 样式控制失效

### ISSUE THREAD

**Issue by missile-xuan** [pipipi-pikachu/PPTist#31]
富文本元素切换页面后 样式控制失效

在切换页面后 再次通过右侧样式控制台编辑富文本样式报错
![image](https://user-images.githubusercontent.com/38873815/119619469-9c9d5480-be36-11eb-886d-6b3bfc002dce.png)
看起来像emit丢了

**Comment by missile-xuan** [comment]
描述的有点问题 重新描述一下
1.编辑富文本通过右侧控制台修改样式
2.修改后不要点击其他地方移除焦点
3.直接新增幻灯片
4.在回到上次操作的页面 通过控制台修改样式 就会复现报错

**Comment by pipipi-pikachu** [comment]
元素编辑状态下直接添加新页面时未清空激活元素的状态导致的，现已修复
