### ISSUE TITLE
[Bug report] ColorPicker

### ISSUE THREAD

**Issue by JuntaoDong** [pipipi-pikachu/PPTist#32]
**问题描述**  

在使用ColorPicker过程中，拖拽Saturation board时会导致Hue picker的值发生改变，进而会改变Saturation board的底色。
![colorpicker](https://user-images.githubusercontent.com/28266824/119713662-8e940780-be27-11eb-8307-1838502dfefe.gif)

**环境信息**  
至少包含以下部分：
1. 系统环境: Windows
2. 浏览器环境：Chrome Version 90.0.4430.212 (Official Build) (64-bit)

**Comment by pipipi-pikachu** [comment]
感谢反馈，问题现已修复
