### ISSUE TITLE
[Bug report]插入文字后不进行输入 直接操作样式属性会出现问题

### ISSUE THREAD

**Issue by missile-xuan** [pipipi-pikachu/PPTist#33]
**问题描述**  
插入富文本控件后直接通过editorView.dispatch修改样式
会因为store中数据还未更新 
在富文本聚焦函数handleFocus中 props.elementInfo.content 的值还是 '请输入内容'
导致dom被清空 致使富文本报错

**Comment by pipipi-pikachu** [comment]
暂时调整了聚焦新添加文本框时的行为来修复该问题。（由 '清空' 改为了 '全选'）
后面应该会再优化新添加文本框的交互
