### ISSUE TITLE
支持插入视频。

### ISSUE THREAD

**Issue by qiuquanwu** [pipipi-pikachu/PPTist#34]
啥时候能支持插入视频。

**Comment by pipipi-pikachu** [comment]
计划中是不准备支持视频的。
个人认为有视频功能需求的并不多，但是要引入巨大的视频播放器插件性价比就很低。
其次视频的实现相比现在的几个元素来说其实非常简单，很容易就能自行按需扩展实现。

我准备将这个问题开放一段时间，看看更多人的建议。

**Comment by jiakunguo** [comment]
放个iframe？

**Comment by wangyue3721** [comment]
就目前来看视频应该是有需求的

**Comment by pipipi-pikachu** [comment]
最近打算自己造一个最小化的播放器，

我的设想是只提供最常用的一些的功能，以较小的成本满足基本需求的前提下，有需要的使用者可以自行扩展，例如自己引入hls. js来支持对应的格式，甚至直接使用一些强大的播放器组件来代替原生的播放器
