### ISSUE TITLE
[Bug report]表格元素切换其他元素报错问题

### ISSUE THREAD

**Issue by missile-xuan** [pipipi-pikachu/PPTist#35]
**问题描述**  
创建表格后 点击或创建其他元素
会报错
![image](https://user-images.githubusercontent.com/38873815/121138556-6914ee00-c86a-11eb-8848-1017e68ce4a5.png)
查了下原因
emitter.on(EmitterEvents.UPDATE_TABLE_SELECTED_CELL, cells => updateSelectedCells(cells))
updateSelectedCells此方法中表格丢失焦点也会调用 
虽然代码执行emitter.off卸载但是 会先执行  updateSelectedCells 
当执行的时候 handleElement已经变成了其他的元素  handleElement.value.data[rowIndex][colIndex].style就报错了
貌似执行中报错导致数据更新不掉 之后的点击会一直报错

![image](https://user-images.githubusercontent.com/38873815/121140209-281dd900-c86c-11eb-9942-ed5d344428af.png)
我加了个判断貌似可以了 但不知道会不会影响其他地方  
大佬看看

**Comment by missile-xuan** [comment]
发现我改完 
emitter.off(EmitterEvents.UPDATE_TABLE_SELECTED_CELL, cells => updateSelectedCells(cells))
虽然执行了卸载 但是点击单元格还是会调用updateSelectedCells  迷
大佬看看吧

**Comment by pipipi-pikachu** [comment]
你这么改没问题的。

然后我也发现了，emitter这块确实有些问题，会重复监听，晚一些我再检查一下

**Comment by pipipi-pikachu** [comment]
一个低级错误..这才是卸载事件的正确写法
```
emitter.on(EmitterEvents.UPDATE_TABLE_SELECTED_CELL, updateSelectedCells)
onUnmounted(() => {
  emitter.off(EmitterEvents.UPDATE_TABLE_SELECTED_CELL, updateSelectedCells)
})
```

> 你这么改没问题的。
> 
> 然后我也发现了，emitter这块确实有些问题，会重复监听，晚一些我再检查一下
