### ISSUE TITLE
[Bug report]表格元素样式 TableStylePanel.vue 中 emitter.on 顺序问题

### ISSUE THREAD

**Issue by missile-xuan** [pipipi-pikachu/PPTist#36]
**问题描述**  
1. 生成一个组表格
2. 切到"位置"编辑窗
3. 给表格加入几个数据
4. 选中其中一个数据
5. 切到”样式“编辑窗
6. 修改样式
7. 发现整个表格的样式都被修改

问题大概是因为TableStylePanel.vue中emitter.on方法在页面打开激活时候才生效，
先选择数据再打开面板导致表格位置数据获取不到， 从而改变整个表格样式

另外生成单元格的时候 这样会导致单元格id都一样 好像不太对 不过暂时没发现什么问题
`
     const rowCells: TableCell[] = new Array(col).fill({ id: createRandomCode(), colspan: 1, rowspan: 1, text: '', style })
     const data: TableCell[][] = new Array(row).fill(rowCells)

    // 我改成循环拿随机id了
    const data: TableCell[][] = new Array(row)
    for (let i = 0 ;i < row; i++) {
      const rowCells: TableCell[] = new Array(col)
      for (let j = 0 ;j < col; j++) {
        rowCells[j] = { id: createRandomCode(), colspan: 1, rowspan: 1, text: '', style }
      }
      data[i] = rowCells
    }
`

**Comment by pipipi-pikachu** [comment]
👍太细心了，单元格ID一样这是个bug，但我很好奇为什么vue没有报错...

至于表格在其他页面操作会导致selectedCells不更新这个问题，我在昨天的 #35 这个问题的处理中就已经发现了，但没有处理，因为我打算这两天抽个时间，把大部分使用mitt的地方都重写下，涉及到状态同步的地方还是vuex更靠谱

**Comment by missile-xuan** [comment]
稳健！
一点一点扒大佬的项目  有用的知识成吨增加  太强了👍
