### ISSUE TITLE
[Bug report]updateTableCells方法多次触发问题

### ISSUE THREAD

**Issue by missile-xuan** [pipipi-pikachu/PPTist#37]
我又来了

**问题描述**  
在修改表格单元格会调用两次updateTableCells方法 第一次传入的还是个string类型

找了下原因
EditableTable.vue中
`
// 单元格文字输入时更新表格数据
    const handleInput = debounce(function(value, rowIndex, colIndex) {
      tableCells.value = tableCells.value[rowIndex][colIndex].text = value
      emit('change', tableCells.value)
    }, 300, { trailing: true })
`
tableCells.value = tableCells.value[rowIndex][colIndex].text = value
会先触发
`
const tableCells = computed<TableCell[][]>({
      get() {
        return props.data
      },
      set(newData) {
        emit('change', newData)
      },
    })
`
中的set

（暂时看起来不影响功能 因为第一次string传进去后 紧接着会被第二次的正确数据覆盖 其他地方还没试）
断点打的我头皮发麻

**Comment by missile-xuan** [comment]
![image](https://user-images.githubusercontent.com/38873815/121326095-d09f6c00-c944-11eb-9853-359136fc6c79.png)

![image](https://user-images.githubusercontent.com/38873815/121326047-bf565f80-c944-11eb-9848-964fb2a46b43.png)

**Comment by pipipi-pikachu** [comment]
这一行是错误的，单纯的手误...现已修复
```
tableCells.value = tableCells.value[rowIndex][colIndex].text = value
```
