### ISSUE TITLE
表格控件文字样式调整后 切换回来样式按钮显示出错

### ISSUE THREAD

**Issue by missile-xuan** [pipipi-pikachu/PPTist#41]
**问题描述**  
创建表格输入文字 修改样式
右侧控制栏切换到动画 
点击其他地方取消选中表格 再点击回表格双击进入编辑 选中修改样式的单元格
再切换回样式控制栏 
发现样式显示为默认样式

**Comment by pipipi-pikachu** [comment]
已修复
