### ISSUE TITLE
创建图表 多列数据时 设置颜色及图例

### ISSUE THREAD

**Issue by missile-xuan** [pipipi-pikachu/PPTist#45]
创建图表 多列数据时 设置颜色及图例

**Comment by pipipi-pikachu** [comment]
计划中会支持设置一系列的图表主题色来用于多列的情况。
至于图例目前没有计划，主要当前使用的图表库（看中它的轻量）不支持，得根据后面的需求来看是否有必要换成其他强大的图表库。
