### ISSUE TITLE
无法本地保存和打开吗

### ISSUE THREAD

**Issue by molin2050** [pipipi-pikachu/PPTist#5]

**Comment by lhyUnited** [comment]
纯前端构建项目，暂时没有该功能。

参见[https://github.com/pipipi-pikachu/PPTist/blob/master/README.md#-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98](https://github.com/pipipi-pikachu/PPTist/blob/master/README.md#-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

**Comment by pipipi-pikachu** [comment]
不太确定你说的本地保存和打开是指什么？

如果是指将数据保存到浏览器或者数据库，那么同楼上所说，暂时不提供该功能，但你可以自行实现，并不复杂~

如果是指保存和打开本地的office PPT，需要拿到在线幻灯片的json数据与office PPT的xml数据进行转换。当然这是个极其复杂的工作，在长期的之中
