### ISSUE TITLE
导入导出讨论

### ISSUE THREAD

**Issue by taoabc** [pipipi-pikachu/PPTist#57]
导出相对简单一些，可以考虑使用：https://github.com/gitbrent/PptxGenJS
导入功能，目前尚未找到合适的库，因为MS的PPTX并没有完全符合OOXML

**Comment by pipipi-pikachu** [comment]
嗯，其实我就是这样打算的.....
之前对PptxGenJS做了一段时间的研究，除了无法绘制自定义形状，基本上能够满足导出的需求，而且绘制自定义形状应该会在PptxGenJS的3.7版本中得到支持，现在就是在等该版本的发布。

实际上之前已经做了一些准备工作了，例如一个将HTML字符串解析器：https://github.com/pipipi-pikachu/PPTist/tree/master/src/utils/htmlParser，后续用来把富文本转化为PptxGenJS需要的格式。

**Comment by pipipi-pikachu** [comment]
导入功能，原本是打算参考 https://github.com/g21589/PPTX2HTML 自己做一个，但是看下来还是很复杂，而且最近也没太多时间，正好继续再想想。

**Comment by taoabc** [comment]
> 导入功能，原本是打算参考 https://github.com/g21589/PPTX2HTML 自己做一个，但是看下来还是很复杂，而且最近也没太多时间，正好继续再想想。

看了下这个库，有段时间了，不知道当时是遇到了什么样的问题～

**Comment by taoabc** [comment]
> 嗯，其实我就是这样打算的.....
> 之前对PptxGenJS做了一段时间的研究，除了无法绘制自定义形状，基本上能够满足导出的需求，而且绘制自定义形状应该会在PptxGenJS的3.7版本中得到支持，现在就是在等该版本的发布。
> 
> 实际上之前已经做了一些准备工作了，例如一个将HTML字符串解析器：https://github.com/pipipi-pikachu/PPTist/tree/master/src/utils/htmlParser 后续用来把富文本转化为PptxGenJS需要的格式。

那太好了，有需要帮忙的话，我看能不能出点力

**Comment by alexwenbj** [comment]
请问一下现在导出的json文件有方法再导进去么？

**Comment by pipipi-pikachu** [comment]
> 请问一下现在导出的json文件有方法再导进去么？

目前不支持，过段时间会补充该功能。
另外在实际生产环境中，该功能应该由后端来完成：上传json文件后，读取并校验数据格式 ，最后将数据设置到slides即可（就是前端store中的那个slides）

**Comment by pipipi-pikachu** [comment]
导出PPTX的功能已上线。
能够实现大多数基本元素的导出，但还有非常多的问题，目前已知的较大的缺陷有：
不支持图片裁剪、不支持图片滤镜、不支持渐变色、不支持图片文字等边框、不支持阴影等...
其他还有一些小问题，目测是可处理的，近期会逐步完善。

**Comment by pipipi-pikachu** [comment]
> 导出PPTX的功能已上线。
> 能够实现大多数基本元素的导出，但还有非常多的问题，目前已知的较大的缺陷有：
> 不支持图片裁剪、不支持图片滤镜、不支持渐变色、不支持图片文字等边框、不支持阴影等...
> 其他还有一些小问题，目测是可处理的，近期会逐步完善。

对于上面提到的这几个问题，在 PptxGenJS 不提供支持的情况下感觉很难解决...有想法的小伙伴欢迎来一起讨论

**Comment by alexwenbj** [comment]
> > 请问一下现在导出的json文件有方法再导进去么？
> 
> 目前不支持，过段时间会补充该功能。
> 另外在实际生产环境中，该功能应该由后端来完成：上传json文件后，读取并校验数据格式 ，最后将数据设置到slides即可（就是前端store中的那个slides）

是的，应该是在后端存储和读取，但如果前端能直接解析json文件为slides就完美了。

**Comment by missile-xuan** [comment]
> > > 请问一下现在导出的json文件有方法再导进去么？
> > 
> > 
> > 目前不支持，过段时间会补充该功能。
> > 另外在实际生产环境中，该功能应该由后端来完成：上传json文件后，读取并校验数据格式 ，最后将数据设置到slides即可（就是前端store中的那个slides）
> 
> 是的，应该是在后端存储和读取，但如果前端能直接解析json文件为slides就完美了。

前端导入自己代码拉下来写一下就可以了吧，因为不是普适需求 感觉直接在原始项目上加也不合适

**Comment by Miazzy** [comment]
什么时候支持在线预览和在线编辑功能，就是给服务器一个PPT的在线地址，可以进行预览和编辑，编辑完成后，可以给个回调地址下载编辑完成的PPT

**Comment by pipipi-pikachu** [comment]
> 什么时候支持在线预览和在线编辑功能，就是给服务器一个PPT的在线地址，可以进行预览和编辑，编辑完成后，可以给个回调地址下载编辑完成的PPT

本项目只是一个【形式上类似 office powerpoint 的在线幻灯片工具】，做不到预览和编辑真实的 .pptx 文件。
与真实的 .pptx 文件的交互只能够依赖导入导出。

你说的这些可以在导入功能上线后自行改造即可，时间不确定，尚在研究中。
另提一句，除非都是自家产品（例如WPS和金山文档），否则两种数据相互转换后都会存在或多或少的差异，所以这种模式可能不适合你的场景。

**Comment by wangyue3721** [comment]
其实可以先把导入json加上，以及导出h5的功能，不用非得等完善以后只针对PPT

**Comment by EastSmartEducation** [comment]
能加个导出h5/图片/pdf功能吗，

**Comment by kankanol1** [comment]
基于该项目，目前实现了国际化（i18n），不知道需不需要？

**Comment by xiaozhou223** [comment]
你好 请问有导出PDF功能没

**Comment by pipipi-pikachu** [comment]
相关计划见 Readme
