### ISSUE TITLE
[Bug report]表格复制粘贴有问题

### ISSUE THREAD

**Issue by missile-xuan** [pipipi-pikachu/PPTist#59]
**问题描述**  
表格复制粘贴有问题

CustomTextarea.vue 中 textareaRef.value.onpaste 方法会更新数据 但是不修改当前页面框体内容

自己尝试了下修复 
因为禁用了原始事件 手动处理粘贴后光标位置有问题 还是大佬看看吧

**Comment by pipipi-pikachu** [comment]
嗯..确实是因为重写了粘贴事件导致的
如果用原生的粘贴，可能会粘贴进来一些奇奇怪怪的东西...
重写后又会有一些同步问题或者光标位置的问题，还不太好处理...
目前暂时先利用[execCommand](https://developer.mozilla.org/zh-CN/docs/Web/API/Document/execCommand)这个已经废弃的API做了临时的处理
