### ISSUE TITLE
请问如何给选定的slide添加子slide，形成树形结构。

### ISSUE THREAD

**Issue by ashfengh** [pipipi-pikachu/PPTist#6]
请问如何给选定的slide添加子slide，形成树形结构。如果开发的话该如何实现呢？

**Comment by pipipi-pikachu** [comment]
你可以尝试在slide下面添加存放子slides的属性（[见对Slide的定义](https://github.com/pipipi-pikachu/PPTist/blob/master/src/types/slides.ts)）
例如：
```
interface Slide {
  id: string;
  elements: PPTElement[];
  background?: SlideBackground;
  animations?: PPTAnimation[];
  turningMode?: 'no' | 'fade' | 'slideX' | 'slideY';
  // add
  subSlides: Slide[];
}
```
然后在vuex中补充相关的一系列方法，再有重点需要根据你的需求一步步调整UI交互逻辑，中途可能会遇到一些问题，但预想中应该都是可以解决的。

**Comment by pipipi-pikachu** [comment]
你可以尝试在slide下面添加存放子slides的属性（[见对Slide的定义](https://github.com/pipipi-pikachu/PPTist/blob/master/src/types/slides.ts)）
例如：
```
interface Slide {
  id: string;
  elements: PPTElement[];
  background?: SlideBackground;
  animations?: PPTAnimation[];
  turningMode?: 'no' | 'fade' | 'slideX' | 'slideY';
  // add
  subSlides: Slide[];
}
```
然后在vuex中补充相关的一系列方法，再有重点需要根据你的需求一步步调整UI交互逻辑，中途可能会遇到一些问题，但预想中应该都是可以解决的。

**Comment by ashfengh** [comment]
> 你可以尝试在slide下面添加存放子slides的属性（[见对Slide的定义](https://github.com/pipipi-pikachu/PPTist/blob/master/src/types/slides.ts)）
> 例如：
> 
> ```
> interface Slide {
>   id: string;
>   elements: PPTElement[];
>   background?: SlideBackground;
>   animations?: PPTAnimation[];
>   turningMode?: 'no' | 'fade' | 'slideX' | 'slideY';
>   // add
>   subSlides: Slide[];
> }
> ```
> 
> 然后在vuex中补充相关的一系列方法，再有重点需要根据你的需求一步步调整UI交互逻辑，中途可能会遇到一些问题，但预想中应该都是可以解决的。

谢谢回答 我试试
