### ISSUE TITLE
建议添加本地存储功能

### ISSUE THREAD

**Issue by cuilei5205189** [pipipi-pikachu/PPTist#65]
关闭网页或者刷新网页，数据就没了。或许可以把本地数据存储在 Local Storge 里。
另外，对这个项目很感兴趣，作者有下一步的开发计划吗？比如未来打算添加什么功能？

**Comment by pipipi-pikachu** [comment]
localstorge 不行哦，数据量大点就放不下了，只能是indexeddb。
言归正传，我的想法是这样的，首先这个项目本身并没有打算作为工具向大众提供服务，只是提供给有需要的人拉取代码后自己进行改造和补充。虽然保存功能很重要，但是本地存储和真实的数据库存储其实完全不一样，对真正面向的使用者其实也就没什么帮助。所以之前虽然有人提出过这个需求但是一直没做。
现在我想的是，这个功能我还是加上，可能确实也有人会有这样的需求。但是时间得稍微往后些，我抽空整理下，确定数据结构完全稳定下来再开始（毕竟要存下来，存储数据的结构肯定就不方便大改了）

**Comment by pipipi-pikachu** [comment]
关于后续的计划我另开了个issue，可以来这里一起讨论 https://github.com/pipipi-pikachu/PPTist/issues/66

**Comment by hashwing** [comment]
@pipipi-pikachu 可以提供一下自定义存储相关文档说明吗？

**Comment by pipipi-pikachu** [comment]
> @pipipi-pikachu 可以提供一下自定义存储相关文档说明吗？

文档晚些吧，忙不过来了😂
存储感觉没啥好说的..
[https://github.com/pipipi-pikachu/PPTist#-%E6%95%B0%E6%8D%AE](https://github.com/pipipi-pikachu/PPTist#-%E6%95%B0%E6%8D%AE) 见 store 中的 slides 和 theme 两个字段，在合适的时机（例如手动保存，或者监听数据变化后）存入数据库，然后初始化时从后台拿到这些数据填到 store 中

**Comment by missile-xuan** [comment]
存储一般都是往服务器后台传  我这就是
技术难度基本为0  就是把store里面的数据扔到后台去啊

**Comment by kankanol1** [comment]
不建议将数据存储在前端和数据库，建议文件格式存储，不然加载巨慢

**Comment by pipipi-pikachu** [comment]
已确定不支持本地缓存功能，需自行在服务端实现（建议mongodb或文件存储）。
若要在纯前端保存，可使用专属 .pptist 文件的导入导出功能。

**Comment by liuyiyi-fly** [comment]
请问你们在自定义添加元素的时候没有报错嘛
