### ISSUE TITLE
未来计划（长期）

### ISSUE THREAD

**Issue by pipipi-pikachu** [pipipi-pikachu/PPTist#66]
短期内主要还是会把重心放在导入功能的研究上。

在这里简单说下后续的一些想法，例如：

1、公式元素，这个还没想好具体是做成latex编辑还是可视化编辑。如果做可视化编辑，我看过现有的一些轮子，感觉体验上都不怎么样，所以可能会选择自己实现。

2、动画的强化，目前仅支持入场动画，后面希望补充上退场动画和强调动画，另外是动画的入场方式不仅仅是现在的顺序触发，还需要有跟随上一个动画触发，自动触发等。

3、更多的导出格式，例如PDF、HTML文件。

暂时就这些，再想到其他的会补充在后面。

**Comment by pipipi-pikachu** [comment]
最近vue3.2正式发布了，计划用script setup重构一下。
在此之前打算把VScode插件换成Volar，部分模板代码需要调整。

最后是单元测试估计得找个时间整起来。

**Comment by pipipi-pikachu** [comment]
是否需要一个开发文档.....

**Comment by wangyue3721** [comment]
导出格式也可以添加epub或者自有格式，模板可以改成自适应的，要不改变比例以后会很别扭

**Comment by missile-xuan** [comment]
导出pdf我自己加了个html2canva做成图片pdf了

**Comment by pipipi-pikachu** [comment]
> 导出格式也可以添加epub或者自有格式，模板可以改成自适应的，要不改变比例以后会很别扭

epub感觉不是很常用....有需要的朋友自行解决吧
页面比例这确实是个问题，可能需要提供一个页面自适应比例的功能，还不仅是模板

**Comment by pipipi-pikachu** [comment]
> 导出pdf我自己加了个html2canva做成图片pdf了

👍我后面试试，上一次试用html2canvas是几年前了...当时问题一大堆😂后面 dom-to-image 用的比较多，但是不太适合这个项目（会强制加载全部字体文件导致速度巨慢）

**Comment by wangyue3721** [comment]
视频功能都有了，音频还会远吗

**Comment by newStudent-ls** [comment]
图形 的处理还是比较简单，像ppt里面插入图形大小变化 不是简单的缩放控制，而是控制svg实现效果，像箭头 顺着箭头反方向拖 箭头是不会变形的

**Comment by SOVLOOKUP** [comment]
希望加一个插件系统和插件市场，以发挥社区力量丰富组件、动画等功能

**Comment by flmn** [comment]
看了下代码，写得很规整，学习中，谢谢 @pipipi-pikachu

**Comment by 2720851545** [comment]
确实不错 酷!

**Comment by Lanseria** [comment]
有没有考虑和 `slidev` 结合一下

**Comment by warmhug** [comment]
看了下核心代码都是自己写的、感觉是个大工程，想请教下目前已有的功能、花了作者多少小时？😃

**Comment by pipipi-pikachu** [comment]
> 图形 的处理还是比较简单，像ppt里面插入图形大小变化 不是简单的缩放控制，而是控制svg实现效果，像箭头 顺着箭头反方向拖 箭头是不会变形的

这个后期有规划

**Comment by pipipi-pikachu** [comment]
> 看了下核心代码都是自己写的、感觉是个大工程，想请教下目前已有的功能、花了作者多少小时？😃

初版到现在差不多一年吧，都是周末和晚上弄，中途断了三个月吧大概，倒是没有特别难的技术点，就是细节和边界问题比较多了

**Comment by pipipi-pikachu** [comment]
> 有没有考虑和 `slidev` 结合一下

感觉也不合适啊，受众不同

**Comment by pipipi-pikachu** [comment]
> 有没有考虑和 `slidev` 结合一下

感觉也不合适啊，受众不同

**Comment by pipipi-pikachu** [comment]
后续重点计划：https://github.com/pipipi-pikachu/PPTist#-%E5%90%8E%E7%BB%AD%E8%A7%84%E5%88%92

其他需求可开新的issue
