### ISSUE TITLE
建议形成一个web通用第三方库

### ISSUE THREAD

**Issue by wtwsky** [pipipi-pikachu/PPTist#67]
在线ppt功能很强大，能否形成一个vue、react使用的第三方库，通过npm安装，直接使用ppt组件即可在个人网站上使用。

**Comment by pipipi-pikachu** [comment]
这个不现实，毕竟功能太多太杂且很分散，也很难做个性化配置。
更加合适的做法是拆出很多个模块来作为包发布，然后让使用者自己组合使用，这个基本等于重写一版了，工作量非常大，看后面的计划吧

**Comment by pipipi-pikachu** [comment]
或者也可以考虑只提供核心模块并暴露api供使用者自行构建～

**Comment by wtwsky** [comment]
不需要太多个性化配置，能在自己项目中构建web版在线编辑ppt，导入导出，能保存编辑的ppt的json数据格式，就很棒了，预计能很受欢迎

**Comment by wy2022** [comment]
大佬，有没有计划，写点博客或者掘金文章，分享下

**Comment by alingfeng520** [comment]
赞一个，国内很很少开源在线PPT的，希望能做大做强，能更方便引入项目就更好了。

**Comment by pipipi-pikachu** [comment]
已确认开源版本不会实现/提供该功能。

**Comment by alingfeng520** [comment]
感谢您的来信和支持，非常感谢！！
