### ISSUE TITLE
当PPT页数过多的时候，点击切换，页面加载延迟很高

### ISSUE THREAD

**Issue by fengjinyou** [pipipi-pikachu/PPTist#68]
1. 当左边的Thumbnails对应后台list很多的时候，点击切换加载Canvas很慢
2. 希望“mutations.ts”中针对这个“MutationTypes.UPDATE_SELECTED_SLIDES_INDEX”中切换index的时候，不是重新加载，而是做成原先display：none属性，切换的时候，针对index动态展示。感恩！

**Comment by pipipi-pikachu** [comment]
大概有多大的量？

这边实测在350页（约800kb的数据量）的情况下：
编辑状态切页没有任何延迟；
放映状态翻页有轻微的卡顿；
仅编辑状态进入放映状态时有明显卡顿；

你这应该不是页数过多的问题，可能需要提供更详细的信息来排查问题，比如方便的话可以提供下导出的json文件

**Comment by missile-xuan** [comment]
我这边引入了echart   切换单页数据大的时候出现了卡顿

**Comment by missile-xuan** [comment]
有可能做操作窗口dom隐藏的方案吗？

**Comment by missile-xuan** [comment]
> 大概有多大的量？
> 
> 这边实测在350页（约800kb的数据量）的情况下：
> 编辑状态切页没有任何延迟；
> 放映状态翻页有轻微的卡顿；
> 仅编辑状态进入放映状态时有明显卡顿；
> 
> 你这应该不是页数过多的问题，可能需要提供更详细的信息来排查问题，比如方便的话可以提供下导出的json文件

当单页数据大的时候切换卡顿在原始项目中也可以复现
加入一张体积大些的图片 切换就可以明显感受到卡顿了
![image](https://user-images.githubusercontent.com/38873815/134830019-6a813a63-adf2-4f4a-8e54-3f8c0e0671e8.png)
短的红框是向小页面切换  长的是有大图的页面切换

**Comment by pipipi-pikachu** [comment]
> > 大概有多大的量？
> > 这边实测在350页（约800kb的数据量）的情况下：
> > 编辑状态切页没有任何延迟；
> > 放映状态翻页有轻微的卡顿；
> > 仅编辑状态进入放映状态时有明显卡顿；
> > 你这应该不是页数过多的问题，可能需要提供更详细的信息来排查问题，比如方便的话可以提供下导出的json文件
> 
> 当单页数据大的时候切换卡顿在原始项目中也可以复现
> 加入一张体积大些的图片 切换就可以明显感受到卡顿了
> ![image](https://user-images.githubusercontent.com/38873815/134830019-6a813a63-adf2-4f4a-8e54-3f8c0e0671e8.png)
> 短的红框是向小页面切换 长的是有大图的页面切换
> 
> 附上slides的json文件
> [pptist_slides (2).zip](https://github.com/pipipi-pikachu/PPTist/files/7232563/pptist_slides.2.zip)

我明白了..这个问题我在[常见问题](https://github.com/pipipi-pikachu/PPTist#-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)中有提过：
> 由于本演示项目不依赖后端，插入本地图片实际引用的是Base64，导致数据体积非常大，在真正的生产环境中应该上传图片后引用图片地址，就不会出现这样的情况了。

如我上面测试的，正常一个PPT产生的数据应该是无论如何也不会超过1mb的，但是如果直接加载较大或较多的Base64的图片会导致数据量非常大，比如你附件的json都快30mb了，肯定会卡

**Comment by missile-xuan** [comment]
> > > 大概有多大的量？
> > > 这边实测在350页（约800kb的数据量）的情况下：
> > > 编辑状态切页没有任何延迟；
> > > 放映状态翻页有轻微的卡顿；
> > > 仅编辑状态进入放映状态时有明显卡顿；
> > > 你这应该不是页数过多的问题，可能需要提供更详细的信息来排查问题，比如方便的话可以提供下导出的json文件
> > 
> > 
> > 当单页数据大的时候切换卡顿在原始项目中也可以复现
> > 加入一张体积大些的图片 切换就可以明显感受到卡顿了
> > ![图片](https://user-images.githubusercontent.com/38873815/134830019-6a813a63-adf2-4f4a-8e54-3f8c0e0671e8.png)
> > 短的红框是向小页面切换 长的是有大图的页面切换
> > 附上slides的json文件
> > [pptist_slides (2).zip](https://github.com/pipipi-pikachu/PPTist/files/7232563/pptist_slides.2.zip)
> 
> 我明白了..这个问题我在[常见问题](https://github.com/pipipi-pikachu/PPTist#-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)中有提过：
> 
> > 由于本演示项目不依赖后端，插入本地图片实际引用的是Base64，导致数据体积非常大，在真正的生产环境中应该上传图片后引用图片地址，就不会出现这样的情况了。
> 
> 如我上面测试的，正常一个PPT产生的数据应该是无论如何也不会超过1mb的，但是如果直接加载较大或较多的Base64的图片会导致数据量非常大，比如你附件的json都快30mb了，肯定会卡

是的 这个图片例子比较极端  只是举例说明一下
我这边现在遇到卡顿的场景虽然不是图片大造成的 原理相同，自己增加模块放进去了echart据来生成图表，由于数据量大  切换就造成卡顿了

**Comment by pipipi-pikachu** [comment]
嗯，说下我的看法和计划：
过大的数据量导致卡顿目前很难避免，以后也很难避免，只能尽可能提高卡顿阈值，这不只是切换页面渲染视图的问题，还有包括各种拖拽缩放历史快照等功能也都有不小的负担，其实有一些优化方案，但是成本较高没来得及做的，例如：将快照式历史记录改为命令式、将缩略图做成虚拟列表，这些都能有效提高性能，不过不知道要排到什么时候了，有需求的朋友可以先朝这个方向尝试。
计划过段时间重构下放映状态的渲染方式，这个应该更急些。

另外有点我不太明白的，EChart的数据应该不会很大，理论上和原项目的图表数据量不会有太大区别才对啊？ @missile-xuan

**Comment by Steve245270533** [comment]
因为只要ppt里包含图片，快照会把图片转为base64存入IndexedDB中，而每次的操作（撤销、重做、编辑）又会继续更改快照，随着图片越来越大，IndexedDB存取（序列号、反序列化）的时间会越来越久，导致阻塞页面交互操作。
