### ISSUE TITLE
Safari 无法编辑。

### ISSUE THREAD

**Issue by KnowsCount** [pipipi-pikachu/PPTist#7]
如题。

---

### 详细信息

版本：Version 14.0 (14610.1.28.1.9)
OS：macOS Mojave 10.14.6

**Comment by lhyUnited** [comment]
问题已复现
原因：文本输入框继承了canvas的`-webkit-user-select: none;`
![image](https://user-images.githubusercontent.com/45580233/112713651-564c7780-8f11-11eb-9590-84140bc80c4e.png)
