### ISSUE TITLE
[Bug report]图片旋转后，进行图片裁剪，拖拽异常

### ISSUE THREAD

**Issue by newStudent-ls** [pipipi-pikachu/PPTist#76]
**问题描述**  
图片旋转后，进行图片裁剪，拖拽异常,鼠标位置与裁剪范围 停留在旋转之前的位置

**Comment by newStudent-ls** [comment]
大佬，这个问题能优先处理吗。bug问题 导致功能无法使用

**Comment by pipipi-pikachu** [comment]
> 大佬，这个问题能优先处理吗。bug问题 导致功能无法使用

目前进行了初步的修复：
裁剪后的位置异常已修复。
操作体验上，旋转接近90度倍数的情况已正常，其他角度下还是有些问题。
