### ISSUE TITLE
使用html2canvas导出图片异常

### ISSUE THREAD

**Issue by davisleelx** [pipipi-pikachu/PPTist#82]
你好。
我希望可以将制作的内容全部导出成图片，请问有什么建议吗？

我现在使用html2canvas生成图片来导出，发现很多元素都无法生成。

这个是页面视图的内容
![image](https://user-images.githubusercontent.com/29814063/158780740-7f8e785c-a009-4512-8e5f-52c8dab85ba7.png)
导出图片的效果
![image](https://user-images.githubusercontent.com/29814063/158780857-2699b981-d6f9-4ab2-a395-6291a7f6ae1c.png)

**Comment by davisleelx** [comment]
图片不显示应该是html2canvas跨域引起的。

不过请教一下有没有什么思路，可以批量把每一页都导出成图片呢？

**Comment by pipipi-pikachu** [comment]
你这个应该就是跨域导致的，具体需要去看看html2canvas的处理方式，另外可以尝试一下这个: https://github.com/bubkoo/html-to-image 个人觉得比html2canvas好用，也更轻量。

至于批量导出图片，其实很久之前添加过导出图片功能，后来因为某些原因删除了（[删除之前的代码看这里](https://github.com/pipipi-pikachu/PPTist/blob/d273594e1aa6132c21159065c6fade712e102339/src/views/Editor/EditorHeader/ExportDialog.vue)），具体做法是：导出时临时创建一个组件，把所有页面都集中渲染在这个组件上，然后用上面的工具来导出。当时是把所有页面导成一张图片，你要分开导出多张也是差不多的
