### ISSUE TITLE
如何给特定文字添加链接？

### ISSUE THREAD

**Issue by BOKE2014** [pipipi-pikachu/PPTist#83]
目前添加链接都是以一个文本框为基础的，如何能给选中的特定（部分）文字添加链接？

**Comment by pipipi-pikachu** [comment]
目前不支持，后面可以考虑增强相关文本框的富文本编辑能力来实现

**Comment by BOKE2014** [comment]
@pipipi-pikachu 好的

**Comment by BOKE2014** [comment]
@pipipi-pikachu 好的

**Comment by BOKE2014** [comment]
@pipipi-pikachu 在文字框里直接右键添加链接是以整个文字框为目标的。如果在“样式”里添加链接是可以精确到具体文字的。
