### ISSUE TITLE
讲演者如何在讲演过程中查看讲演者备注？

### ISSUE THREAD

**Issue by BOKE2014** [pipipi-pikachu/PPTist#85]
讲演者如何在讲演过程中查看讲演者备注？

**Comment by pipipi-pikachu** [comment]
已添加[演讲者模式](https://github.com/pipipi-pikachu/PPTist/commit/fe5c3aa234edebb94105844f6d94279fe963fd00)

**Comment by BOKE2014** [comment]
@pipipi-pikachu 谢谢！体验可以！
