### ISSUE TITLE
在线DEMO能不能开放一下移动端编辑权限，就算不好使也可以试一试，特别是iPad

### ISSUE THREAD

**Issue by BOKE2014** [pipipi-pikachu/PPTist#87]
很少有人在移动设备上制作PPT，但是应急的时候修改几个字还是非常有必要的，特别是在iPad上，能不能把在线DEMO的移动端编辑权限开放一下，这样可以试一试体验一下iPad。谢谢！

**Comment by pipipi-pikachu** [comment]
是指不要在移动端下跳转到当前的预览模式吗？这样的话整个样式都得乱掉，根本无法使用。
可以考虑大屏移动设备（如Pad）下不跳转，手机就没必要了，至少得保证能够正常显示，而且计划中本来就是要支持移动端上简单编辑的，现在只是过渡。

**Comment by BOKE2014** [comment]
>

**Comment by BOKE2014** [comment]
好的，谢谢！iPad上使用体验应该是OK的，手机上Layout，UI甚至editor都得优化。希望能够尽快看到作品。在手机上直接做PPT的人不多，但需要应急修改一些文字的场景非常广泛。

**Comment by BOKE2014** [comment]
@pipipi-pikachu iPad上体验OK
