### ISSUE TITLE
播放者视图的反馈，供参考

### ISSUE THREAD

**Issue by BOKE2014** [pipipi-pikachu/PPTist#88]
感谢 @pipipi-pikachu 的快速更新！播放试图很棒。经过测试给一点反馈，供参考。
1、在PC上（非触摸屏）进入播放者视图界面只能点击下方slide而不能用鼠标拖拽，这样就会有一个问题，当slide页面过多部分隐藏的时候只能顺序点击才能找到后面（隐藏部分）的slide，比较麻烦。可否增加鼠标拖拽，这样的用户体验会比较好，便于快速找到后面某一个slide。BTW，iPad（iPad pro）进入播放者视图界面后可以用手指滑动slide，体验不错！
2、在演讲界面可否考虑增加一个激光笔效果的 cursor，这个功能在实际的演讲中非常实用。
3、画笔是一个很好的功能，在很多场景下也非常有用，但是画笔勾勒的标注不是跟随所在页面的，如果不删除会随着翻页出现在每一页slide上包括黑板，这个体验一下子打了很大折扣。
4、黑板写字不方便，要是能简单的实现键盘打字就好了。

非常感谢🙏

**Comment by pipipi-pikachu** [comment]
感谢反馈，
第1条，其实在PC上是可以通过滚动鼠标滚轮来查看两侧缩略图的，体验上来说应该是比拖拽要好的。
2、3条的需求合理，我另开了 issue ，后面排期来处理。#89 #90 
第4点的话，画笔和黑板用的同一个组件，本意希望是一个较轻量的存在，因为对比一些市面上成熟的白板应用，除了打字，还有一些简单形状/线条绘制，甚至是添加便利贴的能力。关于这些功能是否要做/做到什么程度，可能还需要再考虑一下

**Comment by BOKE2014** [comment]
@pipipi-pikachu 感谢！

**Comment by BOKE2014** [comment]
@pipipi-pikachu 作为非专业技术人员关于第4点有一些理解如下：目前一些基于HTML的slide editor是支持全屏编辑的，即：在全屏预览的模式下可以编辑页面，在这种情况下点击“白板”其实就是插入了一张Slide，那么在插入的这张slide上不论是打字，还是划线等其实就变得合理了。这种方式可能与我们的技术构架有冲突，只是提供一个思路。谢谢！

**Comment by BOKE2014** [comment]
@pipipi-pikachu 关于反馈问题第一条，做了测试。确实通过鼠标滚轴很方便。如果没有鼠标，用键盘的左右键，就只能顺序翻页，使用触摸板是不行的（Mac book air)。再有就是演示模式下（单纯的演示模式没有点击讲演者模式），要点击两次ESC才能回到编辑模式。谢谢！

**Comment by pipipi-pikachu** [comment]
> @pipipi-pikachu 关于反馈问题第一条，做了测试。确实通过鼠标滚轴很方便。如果没有鼠标，用键盘的左右键，就只能顺序翻页，使用触摸板是不行的（Mac book air)。再有就是演示模式下（单纯的演示模式没有点击讲演者模式），要点击两次ESC才能回到编辑模式。谢谢！

触摸板可以通过特定手势代替鼠标，一般是双指上下滑动
