### ISSUE TITLE
在Safari浏览器中无法进入演示。插入文字后，无法输入文字。

### ISSUE THREAD

**Issue by cokeyang** [pipipi-pikachu/PPTist#9]
在Safari浏览器中无法进入演示。插入文字后，无法输入文字。
<img width="200" alt="image" src="https://user-images.githubusercontent.com/20353452/113226633-3d521680-92c3-11eb-9aad-ba8b0da9d8e9.png">
<img width="251" alt="image" src="https://user-images.githubusercontent.com/20353452/113226661-493dd880-92c3-11eb-8a9b-0514b976dc77.png">

**Comment by pipipi-pikachu** [comment]
#7 问题已经解决了的，只是demo未更新，你可以拉取最新代码运行
