### ISSUE TITLE
能否为触摸屏电脑添加文字框拖拽功能

### ISSUE THREAD

**Issue by BOKE2014** [pipipi-pikachu/PPTist#91]
经常使用PPT的用户里有一大部分人员从事销售工作，需要到处去演讲，展示，推销，经常需要随时随地的修改PPT，在火车上修改PPT是一个非常常见的场景😭 ，有的时候特别不方便使用鼠标。经过测试（surface，HUWEI，iPad Pro）这些带有触摸屏的设备，有如下两个主要问题：

1、左侧slide缩略图不能通过手指向下滑动（笔记本可以通过绑定的热键“箭头”实现），iPad不行只能改变缩略图的顺序。
2、文字框，形状，图片等元素无法拖拽，如果通过应用本身的“位置”坐标来调节实在比较麻烦。

谢谢🙏

**Comment by pipipi-pikachu** [comment]
已添加有限的移动端支持，具体见 [常见问题，移动端相关](https://github.com/pipipi-pikachu/PPTist#-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
