### ISSUE TITLE
大佬，导入功能现在有思路吗？求指点一二

### ISSUE THREAD

**Issue by dremup** [pipipi-pikachu/PPTist#92]

**Comment by BOKE2014** [comment]
同问 @dremup @pipipi-pikachu

**Comment by pipipi-pikachu** [comment]
有需要可参考这个实现：https://github.com/g21589/PPTX2HTML
当然了，这个其实处理得很粗糙，实际要更复杂

**Comment by pipipi-pikachu** [comment]
补充一下，这个功能最好在后端来做，抛开前端和语言等限制，实现过程会轻松不少

**Comment by dremup** [comment]
> 有需要可以参考这个：[https](https://github.com/g21589/PPTX2HTML) ://github.com/g21589/PPTX2HTML 当然了，这个处理很简单，实际上要更复杂

[PPTX2HTML](https://github.com/g21589/PPTX2HTML这个转出来样式差距太大了

**Comment by dremup** [comment]
@pipipi-pikachu请问后端用什么方式最好呢？

**Comment by pipipi-pikachu** [comment]
> @pipipi-pikachu请问后端用什么方式最好呢？

思路都是一样的，大致流程就是：
1、拿到pptx文件解析为xml；
2、将xml转为json；
3、按需求将这个json转为所需的格式；

按照前面给的那个项目为例，第一二步可以借助jszip、tXml之类的工具，github上可以找到很多。重点在第三步，这是个体力活。另外如果存在一些实在不好处理的元素，可以试试先转成图片。

当然，这只是一种简单粗暴纯靠体力怼的方案，算不上好....我也没有找到什么更适合的方案
