### ISSUE TITLE
question

### ISSUE THREAD

**Issue by julius2zhu** [pipipi-pikachu/PPTist#93]
请问导出的json文件，如何再根据这个json文件创建对应的pptx呢？

**Comment by pipipi-pikachu** [comment]
json转pptx文件不在本项目的考虑范围

如果你是指导入json，[这里最后一项](https://github.com/pipipi-pikachu/PPTist#-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)已经提到过了，json内容回填到slides中即可
