### ISSUE TITLE
关于PPTist项目的意向询问

### ISSUE THREAD

**Issue by madlifer** [pipipi-pikachu/PPTist#96]
你好，打扰了。我是Madlifer，一个产品经理。

我的来意是想问一下是否你有兴趣基于PPTist项目做一个商业化的sideproject，这个项目致力于解决  “TOB软件产品销售标准化”的问题，是在PPTist的基础上额外新增功能做的一个SaaS平台，我认为比较有商业化前景。

如果你有兴趣，可以添加我的微信 de_base64(TWFkbGlmZXIxMzM3)  详细了解一下我的构思。

BTW: 本来我是打算拉人来做的，但发现PPTist这个项目对于基础功能的完成度已经很高了，所以就过来找你问一下有没有兴趣。我说的项目应该和PPTist的后续研究方向有一定近似之处，所以大概不会影响到这个开源项目的迭代节奏。

**Comment by pipipi-pikachu** [comment]
感谢认可。🙏
不过因为我本身还有本职工作在，恐怕无暇再分出精力搞别的了。🤷‍♂️
