### ISSUE TITLE
导出pptx格式，动画效果消失

### ISSUE THREAD

**Issue by lyhiving** [pipipi-pikachu/PPTist#97]
**问题描述**  
动画信息丢失
1. 选择给内容添加动画，导出ppt格式，然后用Office PowerPoint 打开
2. 原来设置的动画效果全部都不见了

**环境信息**  
1. 系统环境：Mac
2. 浏览器环境：Chrome v 100.0.4896.127

**Comment by pipipi-pikachu** [comment]
这个目前不支持哦，因为依赖的库不支持该功能，具体见👉 [常见问题](https://github.com/pipipi-pikachu/PPTist#-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) 关于导入导出PPTX文件部分
