### ISSUE TITLE
寻求课程合作

### ISSUE THREAD

**Issue by specialzxw** [pipipi-pikachu/PPTist#99]
hi，刚刚偶然关注到您分享的这个项目，我们对这个项目很感兴趣，想邀请您结合这个项目制作线上实战课程，将您的技术知识分享给更多同学学习。课程制作不仅能帮助您回顾总结所学技术，还可以产生一定的收益，如果你对课程制作感兴趣的话，欢迎直接联系我们的官方合作微信号 “shiyanloukecheng”，期待您的联系。

**Comment by claviering** [comment]
现在的骗子都在GitHub上面找目标了？腾讯黎明计划，MCN 机构等，那个不是吸血的？

到处撒网？

<img width="982" alt="image" src="https://user-images.githubusercontent.com/16227832/165733569-6b2a0d71-7bd8-467e-bec2-c7b62ba3595e.png">
